import fs from 'node:fs';
import { ipcMain } from 'electron';
import PQueue from 'p-queue';
import { IPC } from '../../../shared/ipc-channels';
import { isActive } from '../../../shared/activity-state';
import { SessionRepository } from '../../db/repositories/session-repository';
import { WorktreeManager } from '../../git/worktree-manager';
import { isAutoGeneratedBranch } from '../../git/git-checks';
import { getProjectDb } from '../../db/database';
import {
  getProjectRepos,
  ensureTaskWorktree,
  ensureTaskBranchCheckout,
  createTransitionEngine,
  cleanupTaskResources,
  spawnAgent,
} from '../helpers';
import { resolveProjectContext } from '../helpers/project-repos';
import { applyProfileToLane } from '../../transition-engine/column-strategy';
import { loadTaskProfile } from '../helpers/task-profile';
import { guardActiveNonWorktreeSessions } from './task-move';
import { withTaskLock } from '../task-lifecycle-lock';
import type { IpcContext } from '../ipc-context';
import type { TaskBulkDeleteFailure, TaskBulkDeleteResult, TaskBulkDeleteProgress, TaskDetailViewState } from '../../../shared/types';

/**
 * Cap on concurrent bulk-delete workers. Git mutations serialize through the
 * per-project queue in WorktreeManager.withGitLock, so the fan-out here only
 * helps during the non-git phase (PTY kill, session-dir rm, DB writes). A
 * lower number (2) is deliberately chosen: with higher concurrency, many
 * workers enter the sync DB + fs portion of cleanupTaskSession at the same
 * tick, producing a burst of sync work that starves other IPC handlers and
 * makes the renderer feel unresponsive even though its own event loop is
 * fine. 2 gives us some overlap without the burst effect.
 */
const BULK_DELETE_CONCURRENCY = 2;

/**
 * Minimum wall-clock gap between TASK_BULK_DELETE_PROGRESS emissions. Below
 * this the renderer gets flooded with re-renders that compete with user
 * interactions for the React scheduler. The final emission is always sent
 * unthrottled so the UI always reflects the terminal state.
 */
const PROGRESS_THROTTLE_MS = 100;

/**
 * Wall-clock ceiling on per-task cleanup so a single hung op (network drive,
 * corrupted `.git/worktrees/*` metadata) can't poison the bulk-delete queue.
 * Cleanup normally finishes in <5s; this only fires on real hangs. The DB
 * row is still deleted on timeout and the failure surfaces in the UI.
 *
 * Sized to comfortably contain the worst-case git path inside `removeWorktree`
 * (3 sequential `runGitWithTimeout` ops at 15s each) plus the fs-rm fallback,
 * so even a fully-pathological git stall surfaces as the inner timeout.
 */
const TASK_CLEANUP_TIMEOUT_MS = 60_000;

/**
 * Race an operation against a wall-clock deadline. Resolves with the
 * operation's value if it completes in time, otherwise rejects with a
 * descriptive Error. The operation keeps running in the background after
 * the timeout - Node has no generic way to cancel an in-flight simple-git
 * child process, so the best we can do is abandon the promise and let the
 * process exit on its own schedule. This is acceptable because the stuck
 * resource is already broken; we're just refusing to block the batch on it.
 */
function withDeadline<T>(
  operation: () => Promise<T>,
  timeoutMs: number,
  timeoutMessage: string,
): Promise<T> {
  let timeoutHandle: NodeJS.Timeout | undefined;
  const deadline = new Promise<never>((_, reject) => {
    timeoutHandle = setTimeout(
      () => reject(new Error(`Timed out after ${timeoutMs}ms: ${timeoutMessage}`)),
      timeoutMs,
    );
  });
  return Promise.race([
    operation().finally(() => { if (timeoutHandle) clearTimeout(timeoutHandle); }),
    deadline,
  ]);
}

export function registerTaskCrudHandlers(context: IpcContext): void {
  ipcMain.handle(IPC.TASK_LIST, (_, swimlaneId?) => {
    const { tasks } = getProjectRepos(context);
    return tasks.list(swimlaneId);
  });

  ipcMain.handle(IPC.TASK_CREATE, async (_, input, projectId?: string | null) => {
    const { projectId: resolvedProjectId, projectPath: resolvedProjectPath } = resolveProjectContext(context, projectId);
    const { tasks, swimlanes, actions, attachments } = getProjectRepos(context, resolvedProjectId);
    const { pendingAttachments, ...taskInput } = input;
    const task = tasks.create(taskInput);

    // Save any pending attachments from the dialog
    if (pendingAttachments?.length && resolvedProjectPath) {
      for (const att of pendingAttachments) {
        attachments.add(resolvedProjectPath, task.id, att.filename, att.data, att.media_type);
      }
    }

    // Auto-spawn: if target column has auto_spawn, start the agent.
    // Folded through the task's Board Profile so a profile that turns
    // auto_spawn on (or off) for this column is honored at creation, exactly as
    // it is on the move path.
    const toLane = applyProfileToLane(
      swimlanes.getById(task.swimlane_id),
      loadTaskProfile(context, task, resolvedProjectPath),
    );
    if (toLane?.auto_spawn && resolvedProjectPath && resolvedProjectId) {
      const projectPath = resolvedProjectPath;
      const projectId = resolvedProjectId;
      // Serialize the spawn flow against any other in-flight lifecycle op
      // (move, suspend, kill, delete) for this freshly created task. Without
      // the lock, a concurrent TASK_DELETE could clean up resources mid-spawn
      // or a TASK_MOVE could race the transition engine.
      await withTaskLock(task.id, async () => {
        try {
          await ensureTaskWorktree(context, task, tasks, projectPath);
        } catch (worktreeError) {
          console.error('[TASK_CREATE] Worktree creation failed:', worktreeError);
          return;
        }

        // Checkout the task's branch in the main repo (non-worktree tasks only).
        // If checkout fails, the task is still created but no agent is spawned.
        try {
          guardActiveNonWorktreeSessions(context, task, tasks);
          await ensureTaskBranchCheckout(task, projectPath);
        } catch (checkoutError) {
          console.error('[TASK_CREATE] Branch checkout failed:', checkoutError);
          return;
        }

        const db = getProjectDb(projectId);
        const sessionRepo = new SessionRepository(db);
        const engine = createTransitionEngine(context, actions, tasks, sessionRepo, attachments, projectId, projectPath);

        // Route through the shared spawn chokepoint (spawn preamble: the
        // first-spawn override lock + agent resolution, then transition
        // actions, fallback spawn, and auto_command delivery). '*' as
        // fromSwimlaneId - no source column on creation, matches wildcard
        // transitions. settingsSourceLane is omitted deliberately: spawnAgent
        // falls back to toLane, and the New Task dialog displayed inherit
        // values against the creation column itself.
        try {
          await spawnAgent({ context, engine, tasks, sessionRepo, task, fromSwimlaneId: '*', toLane, projectId, projectPath, attachments });
        } catch (err) {
          console.error('[TASK_CREATE] Failed to start session:', err);
        }
      });
    }

    return tasks.getById(task.id) ?? task;
  });

  ipcMain.handle(IPC.TASK_UPDATE, async (_, input, projectId?: string | null) => {
    const { projectId: resolvedProjectId, projectPath: resolvedProjectPath } = resolveProjectContext(context, projectId);
    const { tasks } = getProjectRepos(context, resolvedProjectId);
    const existing = tasks.getById(input.id);

    // If title changed and task has a worktree branch, try to rename the branch
    if (input.title && existing?.branch_name && existing?.worktree_path
        && isAutoGeneratedBranch(existing.branch_name, existing.id, existing.title)
        && input.title !== existing.title && resolvedProjectPath
        && !existing.pr_url) {
      // Guard: skip if the agent is actively thinking (git operations may be in flight)
      const taskSession = context.sessionManager.listSessions()
        .find(s => s.taskId === input.id && (s.status === 'running' || s.status === 'queued'));
      const activityCache = context.sessionManager.getActivityCache();
      const isThinking = taskSession && isActive(activityCache[taskSession.id]);

      if (isThinking) {
        console.log(`[TASK_UPDATE] Skipping branch rename - task ${input.id.slice(0, 8)} agent is thinking`);
      } else if (!fs.existsSync(existing.worktree_path)) {
        console.log(`[TASK_UPDATE] Skipping branch rename - worktree path missing: ${existing.worktree_path}`);
      } else {
        const worktreeManager = new WorktreeManager(resolvedProjectPath);
        const effectiveConfig = context.configManager.getEffectiveConfig(resolvedProjectPath);
        const boardDefaultBranch = context.boardConfigManager.getDefaultBaseBranch();
        const defaultBaseBranch = boardDefaultBranch || effectiveConfig.git.defaultBaseBranch || 'main';
        const newBranchName = await worktreeManager.withLock(
          () => worktreeManager.renameBranch(input.id, existing.branch_name!, input.title, {
            baseBranch: existing.base_branch,
            defaultBaseBranch,
          }),
          { label: `rename-branch:${input.id.slice(0, 8)}` },
        );
        if (newBranchName) {
          console.log(`[TASK_UPDATE] Branch renamed: ${existing.branch_name} -> ${newBranchName}`);
          input.branch_name = newBranchName;
        } else {
          console.log(`[TASK_UPDATE] Branch rename skipped (same slug or failed) for ${existing.branch_name}`);
        }
      }
    }

    return tasks.update(input);
  });

  // Persist the task-detail dialog's layout blob (debounced from the renderer).
  // Single synchronous, single-column write that is independent of session /
  // swimlane lifecycle state, so it deliberately takes NO withTaskLock: there
  // is no await boundary to race across, and a view-state save must not queue
  // behind an in-flight spawn/resume. resolveProjectContext keeps it
  // project-scoped (project-scoped-ipc rule).
  ipcMain.handle(IPC.TASK_SET_DETAIL_VIEW_STATE, (_, taskId: string, state: TaskDetailViewState | null, projectId?: string | null) => {
    const { projectId: resolvedProjectId } = resolveProjectContext(context, projectId);
    if (!resolvedProjectId) return;
    const { tasks } = getProjectRepos(context, resolvedProjectId);
    tasks.setDetailViewState(taskId, state ? JSON.stringify(state) : null);
  });

  ipcMain.handle(IPC.TASK_DELETE, async (_, id, projectId?: string | null) => {
    const { projectId: resolvedProjectId, projectPath: resolvedProjectPath } = resolveProjectContext(context, projectId);
    const { tasks, attachments } = getProjectRepos(context, resolvedProjectId);
    // Serialize against any in-flight session lifecycle op for this task so
    // the long awaits inside cleanup don't race with spawn/resume/etc.
    await withTaskLock(id, async () => {
      const task = tasks.getById(id);
      if (task) {
        attachments.deleteByTaskId(id);
        await cleanupTaskResources(context, task, tasks, resolvedProjectId, resolvedProjectPath);
      }
      tasks.delete(id);
    });
    drainAutoNameAskedIds(context, [id]);
  });

  ipcMain.handle(IPC.TASK_BULK_DELETE, async (_, ids: string[], projectId?: string | null): Promise<TaskBulkDeleteResult> => {
    const { projectId: resolvedProjectId, projectPath: resolvedProjectPath } = resolveProjectContext(context, projectId);
    const { tasks, attachments } = getProjectRepos(context, resolvedProjectId);
    const failures: TaskBulkDeleteFailure[] = [];
    const total = ids.length;
    let completed = 0;

    let lastEmitAt = 0;
    const sendProgress = (): void => {
      if (context.mainWindow.isDestroyed()) return;
      const payload: TaskBulkDeleteProgress = {
        completed,
        total,
        failures: failures.slice(),
      };
      context.mainWindow.webContents.send(IPC.TASK_BULK_DELETE_PROGRESS, payload);
      lastEmitAt = Date.now();
    };
    // Throttled emit: per-task progress during the loop is coalesced so the
    // renderer isn't hammered with hundreds of re-renders while a large batch
    // runs. The initial emit (completed=0) and final emit (completed=total)
    // bypass the throttle so the UI always shows start + end states.
    const emitProgress = (options?: { force?: boolean }): void => {
      if (options?.force || Date.now() - lastEmitAt >= PROGRESS_THROTTLE_MS) {
        sendProgress();
      }
    };

    if (total === 0) {
      return { deleted: 0, failures: [] };
    }

    // Fan out with a concurrency cap. Per-task work is already serialized via
    // withTaskLock, and git mutations serialize through the per-project queue
    // inside WorktreeManager.withGitLock, so parallel workers here just
    // overlap the non-git work (PTY exit awaits, session DB writes,
    // attachment deletes) and yield between async boundaries to keep the main
    // process event loop responsive.
    const queue = new PQueue({ concurrency: BULK_DELETE_CONCURRENCY });
    emitProgress({ force: true });

    await queue.addAll(
      ids.map((id) => async () => {
        const shortId = id.slice(0, 8);
        const startedAt = Date.now();
        let cleanupError: unknown = null;
        let worktreePathBefore: string | null = null;
        console.log(`[TASK_BULK_DELETE] start ${shortId}`);

        try {
          await withTaskLock(id, async () => {
            const task = tasks.getById(id);
            worktreePathBefore = task?.worktree_path ?? null;
            if (task) {
              // Cleanup may legitimately take time (git worktree remove + prune)
              // but MUST NOT hang indefinitely. If a simple-git child process
              // stalls, the per-project git lock stays held and every subsequent
              // task queues forever behind it - the whole batch freezes. Deadline
              // ensures we abandon the stuck op and keep draining the queue.
              try {
                await withDeadline(
                  () => cleanupTaskResources(context, task, tasks, resolvedProjectId, resolvedProjectPath),
                  TASK_CLEANUP_TIMEOUT_MS,
                  `cleanupTaskResources for task ${shortId}`,
                );
              } catch (error) {
                cleanupError = error;
                const message = error instanceof Error ? error.message : String(error);
                console.warn(
                  `[TASK_BULK_DELETE] cleanup failed ${shortId}: ${message}. `
                  + `Proceeding with DB delete; orphaned fs state will be reported.`,
                );
              }
            }
            // DB deletion always runs - the user's delete intent is honored even
            // when filesystem cleanup fails or times out. Any orphaned fs state
            // (worktree directory, session dirs) is surfaced via failures[] so
            // the user sees exactly what needs manual cleanup.
            attachments.deleteByTaskId(id);
            tasks.delete(id);
          });

          if (cleanupError) {
            const message = cleanupError instanceof Error ? cleanupError.message : String(cleanupError);
            failures.push({ id, error: message });
          } else if (worktreePathBefore && fs.existsSync(worktreePathBefore)) {
            // cleanupTaskResources succeeded but the directory survived - orphan.
            failures.push({
              id,
              error: `Worktree directory could not be removed: ${worktreePathBefore}`,
            });
          }
        } catch (error) {
          // Reaches here only if withTaskLock itself failed (unexpected).
          const message = error instanceof Error ? error.message : String(error);
          console.error(`[TASK_BULK_DELETE] lock failure ${shortId}:`, error);
          failures.push({ id, error: message });
        } finally {
          completed += 1;
          const elapsed = Date.now() - startedAt;
          const status = cleanupError ? 'done-with-cleanup-failure' : 'done';
          console.log(`[TASK_BULK_DELETE] ${status} ${shortId} in ${elapsed}ms (${completed}/${total})`);
          // Throttled during the loop; the final emit below forces a send
          // so the renderer always sees completed === total.
          emitProgress();
        }
      }),
    );

    // Guarantee the renderer observes the terminal state (bypasses throttle).
    emitProgress({ force: true });

    // Drop the deleted task IDs from the persisted "auto-name asked" set so
    // that array does not grow unboundedly across the lifetime of a project.
    // We drop everything we attempted; for failures the task may still exist
    // and a future spawn would re-ask, which is the correct behavior.
    const failedIds = new Set(failures.map((entry) => entry.id));
    const deletedIds = ids.filter((id) => !failedIds.has(id));
    if (deletedIds.length > 0) {
      drainAutoNameAskedIds(context, deletedIds);
    }

    return { deleted: total - failures.length, failures };
  });
}

/**
 * Remove the given task IDs from `AppConfig.autoNameAskedTaskIds` so the
 * persisted "don't re-ask" set does not accumulate stale entries for tasks
 * the user has deleted. No-op when the config field is absent, no IDs match,
 * or the configManager isn't fully wired (defensive: this drain is a best-
 * effort cleanup, not load-bearing for the delete operation).
 * @internal Exported for unit tests only; not part of the public API.
 */
export function drainAutoNameAskedIds(context: IpcContext, taskIds: string[]): void {
  if (taskIds.length === 0) return;
  const configManager = context.configManager;
  if (typeof configManager?.load !== 'function' || typeof configManager?.save !== 'function') return;
  let config: { autoNameAskedTaskIds?: string[] };
  try {
    config = configManager.load();
  } catch {
    return;
  }
  const current = config.autoNameAskedTaskIds ?? [];
  if (current.length === 0) return;
  const removeSet = new Set(taskIds);
  const next = current.filter((entry) => !removeSet.has(entry));
  if (next.length === current.length) return;
  try {
    configManager.save({ autoNameAskedTaskIds: next });
  } catch {
    // Best-effort - a save failure here just means the next launch sees a
    // slightly larger asked-set. Not worth surfacing to the user.
  }
}
