blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/Sevenflanks/kangentic/discussions
    about: Ask questions, share ideas, or get help from the community.
