/**
 * Turn a string into a filesystem-safe slug.
 * e.g. "Fix login bug (urgent!)" → "fix-login-bug-urgent"
 */
export function slugify(text: string, maxLen = 20): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxLen)
    .replace(/-+$/, '');
}

/**
 * Compose the auto-generated branch name. When branching off a non-default
 * base, the base is encoded as a namespace prefix (with any '/' flattened to
 * '-') so `git branch` / GitHub branch lists group work by base.
 *
 * Example: base='bugfix/inacc-adjustments', default='main',
 * slug='task-title', shortId='ab12cd34'
 *   produces 'bugfix-inacc-adjustments/task-title-ab12cd34'
 *
 * When base equals default (or is empty), the legacy unprefixed form is used:
 *   produces 'task-title-ab12cd34'
 *
 * Collision note: the single-level namespace (flattened base on the left of
 * one '/') means a deeply-nested user-created branch like
 * `feature/sub/task-xyz` can never match this format, but a shallow
 * user-created branch that happens to mirror `<flattened-base>/<slug>-<id>`
 * would be mis-identified by `isAutoGeneratedBranch`. The 8-char shortId is
 * the collision guard; mismatches require a user to manually pick a branch
 * name containing the exact shortId suffix.
 */
export function computeAutoBranchName(
  baseBranch: string,
  defaultBaseBranch: string,
  slug: string,
  shortId: string,
): string {
  const trimmedBase = (baseBranch ?? '').trim();
  const trimmedDefault = (defaultBaseBranch ?? '').trim();
  const suffix = `${slug}-${shortId}`;
  if (!trimmedBase || trimmedBase === trimmedDefault) return suffix;
  const flattenedBase = trimmedBase.replace(/\//g, '-');
  return `${flattenedBase}/${suffix}`;
}
