import simpleGit from 'simple-git';
import { TaskRepository } from '../../db/repositories/task-repository';
import { WorktreeManager, type GitWaitProgress } from '../../git/worktree-manager';
import { isGitRepo, isAutoGeneratedBranch, hasCommits } from '../../git/git-checks';
import { fetchIfStale } from '../../git/fetch-throttle';
import { DEFAULT_AGENT, type Task } from '../../../shared/types';
import { getProjectRepos } from './project-repos';
import { applyProfileToLane } from '../../transition-engine/column-strategy';
import { loadTaskProfile } from './task-profile';
import type { IpcContext } from '../ipc-context';

/**
 * Resolution of the agent that will run this task, for the worktree-skip
 * check. This MUST mirror `resolveTargetAgent`'s chain (task override ->
 * COLUMN PROFILE's rung for this column -> column override -> project default
 * -> global fallback), because skipping the worktree commits us to remote
 * execution: if this function and the spawn-time resolution disagree, a LOCAL
 * agent spawns with `cwd = projectPath` (transition-engine's
 * `task.worktree_path || projectPath` fallback) and runs unisolated in the
 * user's main checkout.
 *
 * The profile tier is why this is not just "read the lane": a task riding a
 * profile that re-points this column at a remote-execution agent must skip the
 * worktree here, exactly as the spawn will.
 *
 * The column layer is read from the task's CURRENT swimlane, which is the
 * destination lane at every call site (the move/create/promote/unarchive
 * flows all commit the row to the destination before the worktree phase).
 */
function resolveWorktreeCheckAgentName(task: Task, context: IpcContext, projectPath: string): string {
  if (task.agent_override) return task.agent_override;
  const project = context.projectRepo.list().find((candidate) => candidate.path === projectPath);
  if (project?.id && task.swimlane_id) {
    const { swimlanes } = getProjectRepos(context, project.id);
    const lane = applyProfileToLane(
      swimlanes.getById(task.swimlane_id),
      loadTaskProfile(context, task, projectPath),
    );
    if (lane?.agent_override) return lane.agent_override;
  }
  return project?.default_agent ?? DEFAULT_AGENT;
}

/**
 * Create a worktree for a task if needed and update the DB + task object in place.
 * No-ops when worktrees are disabled, the project isn't a git repo, the repo has no commits yet
 * (unborn HEAD), or the resolved agent's execution mode for this project is 'remote' (the agent
 * runs against a server-side directory instead - see `agent.execution` in AppConfig and
 * `ResolvedExecutionTarget`; `task.worktree_path` stays null so `cwd` falls back to the project
 * path, per transition-engine.ts).
 * Throws on worktree creation failure (e.g. duplicate branch, or an unresolvable base branch).
 */
export async function ensureTaskWorktree(
  context: IpcContext,
  task: Task,
  tasks: TaskRepository,
  projectPath?: string | null,
  options?: { signal?: AbortSignal; onProgress?: (phase: string) => void; onWaitProgress?: (info: GitWaitProgress) => void },
): Promise<void> {
  options?.signal?.throwIfAborted();
  const resolvedProjectPath = projectPath ?? context.currentProjectPath;
  if (!resolvedProjectPath) return;
  const config = context.configManager.getEffectiveConfig(resolvedProjectPath);
  const agentName = resolveWorktreeCheckAgentName(task, context, resolvedProjectPath);
  if (config.agent.execution[agentName]?.mode === 'remote') return;
  // No-commits and base-branch-resolution guards live inside
  // WorktreeManager.ensureWorktree (via resolveWorktreeBase) so every caller - this one, the
  // create_worktree transition action, MCP auto-spawn - gets identical behavior.
  const worktreeManager = new WorktreeManager(resolvedProjectPath);
  const result = await worktreeManager.withLock(
    () => worktreeManager.ensureWorktree(task, config.git, { onProgress: options?.onProgress, signal: options?.signal }),
    { label: `create-worktree:${task.id.slice(0, 8)}`, onWaitProgress: options?.onWaitProgress },
  );
  if (result) {
    tasks.update({ id: task.id, worktree_path: result.worktreePath, branch_name: result.branchName });
    Object.assign(task, tasks.getById(task.id));
  }
}

/**
 * Checkout the task's branch in the main repo for non-worktree tasks.
 *
 * Custom branch names (not matching the auto-generated pattern) are fetched
 * from origin, created from base_branch or remote if needed, then checked out.
 * Auto-generated branches fall through to the base_branch checkout path.
 *
 * No-ops when: no project path, task uses a worktree, not a git repo,
 * or task has neither a custom branch_name nor a base_branch.
 * Throws on dirty repo or checkout failure so the caller can block agent spawn.
 */
export async function ensureTaskBranchCheckout(
  task: Task,
  projectPath?: string | null,
  options?: { signal?: AbortSignal; onProgress?: (phase: string) => void; onWaitProgress?: (info: GitWaitProgress) => void },
): Promise<void> {
  options?.signal?.throwIfAborted();
  if (!projectPath) return;
  if (task.worktree_path) return;
  if (!isGitRepo(projectPath)) return;

  const usesCustomBranch = Boolean(
    task.branch_name && !isAutoGeneratedBranch(task.branch_name, task.id, task.title),
  );
  // Nothing to check out either way, so stop before touching git at all.
  if (!usesCustomBranch && !task.base_branch) return;
  // Same unborn-HEAD case WorktreeManager.ensureWorktree guards for the worktree path: with no
  // commits there is no branch to fetch, create, or check out, and every git call below would
  // fail on the ref. Deliberately AFTER the cheap guards - it shells out, and the common move
  // has no branch work to do.
  if (!(await hasCommits(projectPath))) return;

  // Custom branch name: fetch latest, create if needed, then checkout
  if (usesCustomBranch) {
    await WorktreeManager.withGitLock(projectPath, async () => {
      const git = simpleGit(projectPath);

      // Emit 'fetching' once the job actually starts (after any queue wait) so
      // the card flips from the "Waiting..." label to "Fetching latest...".
      options?.onProgress?.('fetching');
      // Fetch latest from origin (throttled to avoid redundant network I/O)
      await fetchIfStale(git, projectPath, task.branch_name!, { signal: options?.signal });
      options?.onProgress?.('switching-branch');
      options?.signal?.throwIfAborted();

      // Check if branch exists locally (user's local may be ahead of remote, that's fine)
      let branchExists = false;
      try {
        await git.raw(['rev-parse', '--verify', task.branch_name!]);
        branchExists = true;
      } catch {
        // Branch does not exist locally
      }

      if (!branchExists) {
        // Check if it exists on remote (we already fetched above)
        let existsOnRemote = false;
        try {
          await git.raw(['rev-parse', '--verify', `origin/${task.branch_name}`]);
          existsOnRemote = true;
        } catch {
          // Not on remote either
        }

        if (existsOnRemote) {
          // Create local branch tracking the remote
          await git.raw(['branch', task.branch_name!, `origin/${task.branch_name}`]);
        } else {
          // Branch doesn't exist anywhere. Create from base_branch.
          const baseBranch = task.base_branch || 'main';
          await git.raw(['branch', task.branch_name!, baseBranch]);
        }
      }

      const worktreeManager = new WorktreeManager(projectPath);
      await worktreeManager.checkoutBranch(task.branch_name!);
    }, { label: `checkout-branch:${task.id.slice(0, 8)}`, onWaitProgress: options?.onWaitProgress });
    return;
  }

  // Fall through to existing base_branch checkout logic. `usesCustomBranch` being false
  // already guarantees a base_branch above; this narrows it for TypeScript.
  if (!task.base_branch) return;

  const worktreeManager = new WorktreeManager(projectPath);
  await worktreeManager.withLock(async () => {
    // Once the job actually starts (after any queue wait), flip the card from
    // the "Waiting..." label to an active label for the duration of the checkout.
    options?.onProgress?.('switching-branch');
    await worktreeManager.checkoutBranch(task.base_branch!);
  }, { label: `checkout-branch:${task.id.slice(0, 8)}`, onWaitProgress: options?.onWaitProgress });
}
