/**
 * The checkout-occupancy guard: no `git checkout` may run in a working directory
 * where another task already has a live agent.
 *
 * The guard used to live in `task-move.ts` keyed on `task.base_branch`, while the
 * decision to check out is keyed on `usesCustomBranch || base_branch`. A task
 * with a custom branch and no base branch therefore checked out with the guard
 * never running, changing the working tree under someone else's agent. The first
 * test below is that case and fails against the pre-fix code.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import path from 'node:path';

/**
 * The two locks are stubbed as pass-throughs here so these tests isolate the
 * guard. That is only sound because the REAL per-project git queue is already
 * pinned to propagate a rejecting callback out to its caller, in
 * `worktree-manager.test.ts` ("a failing operation rejects", "a thrown
 * high-priority op does not wedge the runner"). If that ever stopped holding,
 * the guard would throw into a queue that swallowed it and these tests would
 * still pass, so the two files are load-bearing together.
 */
const ensureWorktreeMock = vi.fn();
const checkoutBranchMock = vi.fn();
const withGitLockMock = vi.fn(async (_projectPath: string, body: () => Promise<void>) => body());
const withLockMock = vi.fn(async (body: () => Promise<void>) => body());

vi.mock('../../src/main/git/worktree-manager', () => ({
  WorktreeManager: class {
    static withGitLock = (projectPath: string, body: () => Promise<void>) =>
      withGitLockMock(projectPath, body);
    ensureWorktree = ensureWorktreeMock;
    checkoutBranch = checkoutBranchMock;
    withLock = (body: () => Promise<void>) => withLockMock(body);
  },
}));

vi.mock('../../src/main/git/git-checks', () => ({
  isGitRepo: vi.fn(() => true),
  hasCommits: vi.fn(async () => true),
  // Anything not ending in the task's shortId reads as a user-authored branch.
  isAutoGeneratedBranch: vi.fn((branchName: string) => branchName.endsWith('-abcd1234')),
}));

vi.mock('../../src/main/git/fetch-throttle', () => ({ fetchIfStale: vi.fn(async () => 'main') }));

vi.mock('simple-git', () => ({
  default: () => ({ raw: vi.fn(async () => '') }),
}));

import { ensureTaskBranchCheckout, BranchCheckoutBlockedError } from '../../src/main/ipc/helpers/task-git';
import type { IpcContext } from '../../src/main/ipc/ipc-context';
import type { Task } from '../../src/shared/types';

const PROJECT_PATH = path.join('C:', 'Users', 'dev', 'proj');

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: 'aaaa1111-0000-0000-0000-000000000000',
    display_id: 1,
    title: 'A task',
    worktree_path: null,
    worktree_folder: null,
    branch_name: null,
    base_branch: null,
    ...overrides,
  } as Task;
}

/** A context whose session list is exactly the supplied sessions. */
function makeContext(sessions: Array<{ taskId: string; status: string; cwd: string }>): IpcContext {
  return {
    sessionManager: { listSessions: () => sessions },
    // Naming the blocking task is best effort; a throwing repo must not change
    // the outcome, which this deliberately exercises.
    currentProjectId: null,
    projectRepo: { list: () => [] },
  } as unknown as IpcContext;
}

describe('ensureTaskBranchCheckout occupancy guard', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    withGitLockMock.mockImplementation(async (_projectPath: string, body: () => Promise<void>) => body());
    withLockMock.mockImplementation(async (body: () => Promise<void>) => body());
  });

  it('blocks a CUSTOM-branch task with no base_branch (the guard hole)', async () => {
    // The exact shape the old guard let through: it returned early on
    // `!task.base_branch` while this task still gets checked out.
    const task = makeTask({ branch_name: 'feature/login', base_branch: null });
    const context = makeContext([
      { taskId: 'other-task', status: 'running', cwd: PROJECT_PATH },
    ]);

    await expect(ensureTaskBranchCheckout(context, task, PROJECT_PATH))
      .rejects.toBeInstanceOf(BranchCheckoutBlockedError);
    expect(checkoutBranchMock).not.toHaveBeenCalled();
  });

  it('still blocks the base_branch case (no regression on the path that worked)', async () => {
    const task = makeTask({ base_branch: 'develop' });
    const context = makeContext([
      { taskId: 'other-task', status: 'running', cwd: PROJECT_PATH },
    ]);

    await expect(ensureTaskBranchCheckout(context, task, PROJECT_PATH))
      .rejects.toBeInstanceOf(BranchCheckoutBlockedError);
    expect(checkoutBranchMock).not.toHaveBeenCalled();
  });

  it('counts a queued session, which holds the directory before its PTY exists', async () => {
    const task = makeTask({ base_branch: 'develop' });
    const context = makeContext([
      { taskId: 'other-task', status: 'queued', cwd: PROJECT_PATH },
    ]);

    await expect(ensureTaskBranchCheckout(context, task, PROJECT_PATH))
      .rejects.toBeInstanceOf(BranchCheckoutBlockedError);
  });

  it('allows the checkout when the only live session is the task itself', async () => {
    const task = makeTask({ base_branch: 'develop' });
    const context = makeContext([
      { taskId: task.id, status: 'running', cwd: PROJECT_PATH },
    ]);

    await ensureTaskBranchCheckout(context, task, PROJECT_PATH);
    expect(checkoutBranchMock).toHaveBeenCalledWith('develop');
  });

  it('allows the checkout when the other agent is in its own worktree', async () => {
    const task = makeTask({ base_branch: 'develop' });
    const context = makeContext([
      {
        taskId: 'other-task',
        status: 'running',
        cwd: path.join(PROJECT_PATH, '.kangentic', 'worktrees', '460'),
      },
    ]);

    await ensureTaskBranchCheckout(context, task, PROJECT_PATH);
    expect(checkoutBranchMock).toHaveBeenCalledWith('develop');
  });

  it('ignores a session that has already exited', async () => {
    const task = makeTask({ base_branch: 'develop' });
    const context = makeContext([
      { taskId: 'other-task', status: 'exited', cwd: PROJECT_PATH },
    ]);

    await ensureTaskBranchCheckout(context, task, PROJECT_PATH);
    expect(checkoutBranchMock).toHaveBeenCalledWith('develop');
  });

  it('never runs for a task that has its own worktree', async () => {
    const task = makeTask({
      base_branch: 'develop',
      worktree_path: path.join(PROJECT_PATH, '.kangentic', 'worktrees', '460'),
    });
    const context = makeContext([
      { taskId: 'other-task', status: 'running', cwd: PROJECT_PATH },
    ]);

    await ensureTaskBranchCheckout(context, task, PROJECT_PATH);
    expect(checkoutBranchMock).not.toHaveBeenCalled();
  });

  /**
   * Windows-only by necessity, not by preference. `isSameDirectory` compares via
   * `path.relative`, and it is `path.win32.relative` that case-folds and treats
   * `\` as a separator. That behaviour comes from the `path` module bound at
   * import time, so spoofing `process.platform` does NOT produce it: on Linux
   * these two strings resolve to two genuinely different directories and the
   * guard correctly does not fire. Run it where the semantics actually exist.
   */
  it.runIf(process.platform === 'win32')(
    'treats separator and drive-case differences as the same directory on Windows',
    async () => {
      const task = makeTask({ base_branch: 'develop' });
      // Same directory, written the way a PTY cwd often comes back.
      const context = makeContext([
        { taskId: 'other-task', status: 'running', cwd: 'c:/Users/dev/proj' },
      ]);

      await expect(ensureTaskBranchCheckout(context, task, 'C:\\Users\\dev\\proj'))
        .rejects.toBeInstanceOf(BranchCheckoutBlockedError);
    },
  );

  /**
   * A Command Terminal spawns a real agent with `cwd = projectRoot`
   * (`handlers/transient-sessions.ts`), so it holds the directory exactly as a
   * task does. The old guard missed it: it resolved each session's taskId to a
   * task row, and a transient id resolves to nothing, so those sessions were
   * silently skipped.
   */
  it('blocks on an open Command Terminal, and says so rather than naming a task', async () => {
    const task = makeTask({ base_branch: 'develop' });
    const context = {
      sessionManager: {
        listSessions: () => [
          { taskId: 'transient-abc', status: 'running', cwd: PROJECT_PATH, transient: true },
        ],
      },
      currentProjectId: null,
      projectRepo: { list: () => [] },
    } as unknown as IpcContext;

    await expect(ensureTaskBranchCheckout(context, task, PROJECT_PATH))
      .rejects.toThrow(/Command Terminal/);
    expect(checkoutBranchMock).not.toHaveBeenCalled();
  });

  it('names the blocking task in the message so the user knows what to stop', async () => {
    const task = makeTask({ base_branch: 'develop' });
    const context = {
      sessionManager: {
        listSessions: () => [{ taskId: 'other-task', status: 'running', cwd: PROJECT_PATH }],
      },
      currentProjectId: 'project-1',
      projectRepo: { list: () => [] },
    } as unknown as IpcContext;

    // The repo lookup is best effort. Even when it cannot resolve a title, the
    // error must still identify the blocker rather than failing to construct.
    await expect(ensureTaskBranchCheckout(context, task, PROJECT_PATH))
      .rejects.toThrow(/other-ta|is already running an agent/);
  });
});
