/**
 * Unit tests for TASK_BULK_DELETE IPC handler.
 *
 * The handler body is extracted by capturing the function registered with
 * ipcMain.handle for IPC.TASK_BULK_DELETE and invoking it directly. All
 * dependencies (fs, getProjectRepos, withTaskLock, cleanupTaskResources,
 * PQueue, ipcMain, electron) are mocked so no Electron binary or real
 * filesystem is needed.
 *
 * Covers:
 *   - empty ids array early return (no progress events, deleted=0, failures=[])
 *   - happy path: all tasks deleted cleanly, deleted=N, failures=[]
 *   - orphan detection: cleanupTaskResources succeeds but directory survives
 *     on disk -> failure pushed with "Worktree directory could not be removed"
 *   - withTaskLock throw path: error caught, pushed to failures, no re-throw
 *   - progress events emitted per task including the initial emit
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ---------------------------------------------------------------------------
// Hoisted mocks
// ---------------------------------------------------------------------------

const { mockExistsSync } = vi.hoisted(() => ({
  mockExistsSync: vi.fn((): boolean => false),
}));

vi.mock('node:fs', () => ({
  default: {
    existsSync: mockExistsSync,
  },
}));

// ipcMain: capture the handler registered for each channel
const capturedHandlers = new Map<string, (...args: unknown[]) => unknown>();
vi.mock('electron', () => ({
  ipcMain: {
    handle: vi.fn((channel: string, handler: (...args: unknown[]) => unknown) => {
      capturedHandlers.set(channel, handler);
    }),
  },
}));

// PQueue: minimal stub that satisfies both the outer concurrency queue
// (uses addAll) and withTaskLock's internal per-task queue (uses add +
// size/pending for cleanup). All tasks run inline, sequentially.
vi.mock('p-queue', () => ({
  default: class {
    size = 0;
    pending = 0;

    async add(fn: () => Promise<unknown>): Promise<unknown> {
      return fn();
    }

    async addAll(tasks: Array<() => Promise<unknown>>): Promise<void> {
      for (const task of tasks) {
        await task();
      }
    }
  },
}));

// simple-git: not exercised by the bulk-delete handler path
vi.mock('simple-git', () => ({
  simpleGit: vi.fn(() => ({})),
  default: vi.fn(() => ({})),
}));

// DB layer: not exercised by bulk-delete handler (getProjectRepos is mocked below)
vi.mock('../../src/main/db/database', () => ({ getProjectDb: vi.fn() }));
vi.mock('../../src/main/db/repositories/task-repository', () => ({
  TaskRepository: class {},
}));
vi.mock('../../src/main/db/repositories/session-repository', () => ({
  SessionRepository: class {},
}));
vi.mock('../../src/main/db/repositories/swimlane-repository', () => ({
  SwimlaneRepository: class {},
}));
vi.mock('../../src/main/db/repositories/action-repository', () => ({
  ActionRepository: class {},
}));
vi.mock('../../src/main/db/repositories/attachment-repository', () => ({
  AttachmentRepository: class {},
}));

// WorktreeManager: not exercised by bulk-delete handler directly
vi.mock('../../src/main/git/worktree-manager', () => ({
  WorktreeManager: class {
    withLock = vi.fn(async (fn: () => Promise<unknown>) => fn());
    removeWorktree = vi.fn(async () => true);
  },
}));

// git-checks: not exercised
vi.mock('../../src/main/git/git-checks', () => ({
  isAutoGeneratedBranch: vi.fn(() => false),
}));

// isGitRepo / isInsideWorktree: not exercised
vi.mock('../../src/main/git/fetch-throttle', () => ({
  fetchIfStale: vi.fn(async () => 'main'),
}));

vi.mock('../../src/main/git/node-modules-link', () => ({
  linkNodeModules: vi.fn(),
  removeNodeModulesPath: vi.fn(),
}));

// task-lifecycle-lock: use the REAL implementation so lock semantics are preserved
// (the handler wraps each task in withTaskLock)

// Mocked helpers - set up per test
const mockGetProjectRepos = vi.fn();
const mockCleanupTaskResources = vi.fn();
const mockEnsureTaskWorktree = vi.fn(async () => null);
const mockEnsureTaskBranchCheckout = vi.fn(async () => {});
const mockCreateTransitionEngine = vi.fn(() => ({}));

vi.mock('../../src/main/ipc/helpers', () => ({
  getProjectRepos: (...args: unknown[]) => mockGetProjectRepos(...args),
  cleanupTaskResources: (...args: unknown[]) => mockCleanupTaskResources(...args),
  ensureTaskWorktree: (...args: unknown[]) => mockEnsureTaskWorktree(...args),
  ensureTaskBranchCheckout: (...args: unknown[]) => mockEnsureTaskBranchCheckout(...args),
  createTransitionEngine: (...args: unknown[]) => mockCreateTransitionEngine(...args),
  interpolateTemplate: vi.fn((template: string) => template),
}));

// agent/shared
vi.mock('../../src/main/agent/shared', () => ({
  interpolateTemplate: vi.fn((template: string) => template),
  resolveBridgeScript: vi.fn(() => '/mock/bridge.js'),
  execVersion: vi.fn(async () => '1.0.0'),
}));

// task-branch
vi.mock('../../src/main/ipc/handlers/task-branch', () => ({
  carryUncommittedChanges: vi.fn(async () => ({
    carriedTracked: false,
    carriedUntracked: [],
    applyFailed: false,
    failedUntracked: [],
  })),
}));

// task-move
vi.mock('../../src/main/ipc/handlers/task-move', () => ({
  handleTaskMove: vi.fn(async () => {}),
  guardActiveNonWorktreeSessions: vi.fn(),
}));

// config manager stubs (used by TASK_UPDATE path, not bulk delete, but needed for module load)
vi.mock('../../src/main/config/config-manager', () => ({
  ConfigManager: class {
    getEffectiveConfig = vi.fn(() => ({ git: { defaultBaseBranch: 'main' } }));
  },
}));

// ---------------------------------------------------------------------------
// Import under test (after all mocks are registered)
// ---------------------------------------------------------------------------

import { registerTaskCrudHandlers } from '../../src/main/ipc/handlers/task-crud';
import { IPC } from '../../src/shared/ipc-channels';

// ---------------------------------------------------------------------------
// Helper types
// ---------------------------------------------------------------------------

interface MockTask {
  id: string;
  title: string;
  worktree_path: string | null;
  session_id: string | null;
  branch_name: string | null;
}

interface MockTaskRepo {
  getById: ReturnType<typeof vi.fn>;
  delete: ReturnType<typeof vi.fn>;
}

interface MockAttachmentRepo {
  deleteByTaskId: ReturnType<typeof vi.fn>;
}

interface MockMainWindow {
  isDestroyed: ReturnType<typeof vi.fn>;
  webContents: { send: ReturnType<typeof vi.fn> };
}

interface MockContext {
  currentProjectId: string | null;
  currentProjectPath: string | null;
  mainWindow: MockMainWindow;
  sessionManager: {
    listSessions: ReturnType<typeof vi.fn>;
    getActivityCache: ReturnType<typeof vi.fn>;
  };
  configManager: {
    getEffectiveConfig: ReturnType<typeof vi.fn>;
  };
  boardConfigManager: {
    getDefaultBaseBranch: ReturnType<typeof vi.fn>;
  };
  terminalSubmitScheduler: {
    scheduleKeystrokes: ReturnType<typeof vi.fn>;
  };
}

function createMockTask(id: string, overrides: Partial<MockTask> = {}): MockTask {
  return {
    id,
    title: `Task ${id}`,
    worktree_path: null,
    session_id: null,
    branch_name: null,
    ...overrides,
  };
}

function createMockTaskRepo(tasks: MockTask[]): MockTaskRepo {
  const taskMap = new Map(tasks.map((task) => [task.id, task]));
  return {
    getById: vi.fn((id: string) => taskMap.get(id) ?? null),
    delete: vi.fn((id: string) => taskMap.delete(id)),
  };
}

function createMockAttachmentRepo(): MockAttachmentRepo {
  return {
    deleteByTaskId: vi.fn(),
  };
}

function createMockContext(): MockContext {
  return {
    currentProjectId: 'proj-123',
    currentProjectPath: '/mock/project',
    mainWindow: {
      isDestroyed: vi.fn(() => false),
      webContents: { send: vi.fn() },
    },
    sessionManager: {
      listSessions: vi.fn(() => []),
      getActivityCache: vi.fn(() => ({})),
    },
    configManager: {
      getEffectiveConfig: vi.fn(() => ({ git: { defaultBaseBranch: 'main' } })),
    },
    boardConfigManager: {
      getDefaultBaseBranch: vi.fn(() => null),
    },
    terminalSubmitScheduler: {
      scheduleKeystrokes: vi.fn(),
    },
  };
}

// Invoke the registered TASK_BULK_DELETE handler directly. The first argument
// (Electron Event object) is omitted since the handler only uses subsequent args.
async function callBulkDeleteHandler(context: MockContext, ids: string[]) {
  const handler = capturedHandlers.get(IPC.TASK_BULK_DELETE);
  if (!handler) throw new Error(`Handler for ${IPC.TASK_BULK_DELETE} was not registered`);
  // The IPC event is unused by this handler - pass null as a stand-in.
  return handler(null, ids) as Promise<{ deleted: number; failures: Array<{ id: string; error: string }> }>;
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe('TASK_BULK_DELETE handler', () => {
  let context: MockContext;
  let taskRepo: MockTaskRepo;
  let attachmentRepo: MockAttachmentRepo;

  beforeEach(() => {
    vi.clearAllMocks();
    capturedHandlers.clear();
    mockExistsSync.mockReturnValue(false);
    mockCleanupTaskResources.mockResolvedValue(undefined);

    context = createMockContext();
    taskRepo = createMockTaskRepo([]);
    attachmentRepo = createMockAttachmentRepo();

    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      attachments: attachmentRepo,
      swimlanes: { list: vi.fn(() => []), getById: vi.fn() },
      actions: { getTransitionsFor: vi.fn(() => []) },
    });

    // Register handlers so capturedHandlers is populated. MockContext
    // implements only the bulk-delete-relevant subset of IpcContext
    // (mainWindow, currentProjectId/Path, sessionManager, configManager,
    // commandInjector). The `as never` cast sidesteps the shape check for
    // unused fields like projectRepo, gitDetector, shellResolver, etc.
    registerTaskCrudHandlers(context as never);
  });

  // -------------------------------------------------------------------------
  // Gap #4: empty ids early return
  // -------------------------------------------------------------------------

  it('returns {deleted:0, failures:[]} immediately for empty ids without emitting progress', async () => {
    const result = await callBulkDeleteHandler(context, []);

    expect(result).toEqual({ deleted: 0, failures: [] });
    // No progress events should be emitted for empty input
    expect(context.mainWindow.webContents.send).not.toHaveBeenCalled();
    expect(mockCleanupTaskResources).not.toHaveBeenCalled();
  });

  // -------------------------------------------------------------------------
  // Happy path: all tasks deleted cleanly
  // -------------------------------------------------------------------------

  it('deletes all tasks cleanly, returns deleted=N, failures=[], forces start and end progress emits', async () => {
    const tasks = [
      createMockTask('task-a'),
      createMockTask('task-b'),
      createMockTask('task-c'),
    ];
    taskRepo = createMockTaskRepo(tasks);
    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      attachments: attachmentRepo,
      swimlanes: { list: vi.fn(() => []), getById: vi.fn() },
      actions: { getTransitionsFor: vi.fn(() => []) },
    });

    // No worktree paths, so fs.existsSync should never be called for these
    mockExistsSync.mockReturnValue(false);

    const result = await callBulkDeleteHandler(context, ['task-a', 'task-b', 'task-c']);

    expect(result.deleted).toBe(3);
    expect(result.failures).toHaveLength(0);
    expect(taskRepo.delete).toHaveBeenCalledTimes(3);
    expect(attachmentRepo.deleteByTaskId).toHaveBeenCalledTimes(3);
    expect(mockCleanupTaskResources).toHaveBeenCalledTimes(3);

    // Contract: the handler forces a progress emit at start (completed=0) and
    // at end (completed=total). Mid-loop emits are throttled and may or may
    // not fire depending on elapsed wall-clock time - we only assert the
    // guaranteed first + last.
    const progressCalls = context.mainWindow.webContents.send.mock.calls.filter(
      (call) => call[0] === IPC.TASK_BULK_DELETE_PROGRESS,
    );
    expect(progressCalls.length).toBeGreaterThanOrEqual(2);

    const firstPayload = progressCalls[0][1] as { completed: number; total: number };
    expect(firstPayload.completed).toBe(0);
    expect(firstPayload.total).toBe(3);

    const lastPayload = progressCalls[progressCalls.length - 1][1] as {
      completed: number; total: number; failures: Array<{ id: string; error: string }>;
    };
    expect(lastPayload.completed).toBe(3);
    expect(lastPayload.total).toBe(3);
    expect(lastPayload.failures).toHaveLength(0);
  });

  // -------------------------------------------------------------------------
  // Gap #1 (HIGH): orphan detection
  // The worktree directory survives on disk after cleanupTaskResources returns.
  // The handler must push a failure entry but still delete the DB row.
  // -------------------------------------------------------------------------

  it('pushes orphan failure when worktree directory survives after cleanup', async () => {
    const worktreePath = '/mock/project/.kangentic/worktrees/task-orphan-abcd';
    const task = createMockTask('task-orphan', { worktree_path: worktreePath });
    taskRepo = createMockTaskRepo([task]);
    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      attachments: attachmentRepo,
      swimlanes: { list: vi.fn(() => []), getById: vi.fn() },
      actions: { getTransitionsFor: vi.fn(() => []) },
    });

    // cleanupTaskResources "succeeds" but the directory is still present
    mockCleanupTaskResources.mockResolvedValue(undefined);
    mockExistsSync.mockImplementation((p: string) => p === worktreePath);

    const result = await callBulkDeleteHandler(context, ['task-orphan']);

    // DB row was still deleted (tasks.delete called)
    expect(taskRepo.delete).toHaveBeenCalledWith('task-orphan');

    // One failure pushed for the orphan
    expect(result.failures).toHaveLength(1);
    expect(result.failures[0].id).toBe('task-orphan');
    expect(result.failures[0].error).toContain('Worktree directory could not be removed');
    expect(result.failures[0].error).toContain(worktreePath);

    // deleted count reflects the failure: total(1) - failures(1) = 0
    expect(result.deleted).toBe(0);
  });

  // -------------------------------------------------------------------------
  // Gap #1 variant: task has worktree_path but directory does NOT exist
  // (already cleaned up by git worktree remove) - should NOT push failure
  // -------------------------------------------------------------------------

  it('does NOT push orphan failure when worktree path is gone after cleanup', async () => {
    const worktreePath = '/mock/project/.kangentic/worktrees/task-clean-abcd';
    const task = createMockTask('task-clean', { worktree_path: worktreePath });
    taskRepo = createMockTaskRepo([task]);
    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      attachments: attachmentRepo,
      swimlanes: { list: vi.fn(() => []), getById: vi.fn() },
      actions: { getTransitionsFor: vi.fn(() => []) },
    });

    mockCleanupTaskResources.mockResolvedValue(undefined);
    // Directory is gone after cleanup
    mockExistsSync.mockReturnValue(false);

    const result = await callBulkDeleteHandler(context, ['task-clean']);

    expect(result.failures).toHaveLength(0);
    expect(result.deleted).toBe(1);
  });

  // -------------------------------------------------------------------------
  // Gap #3 (HIGH): withTaskLock / cleanupTaskResources throw path
  // Error is caught, pushed to failures[], handler does not re-throw.
  // -------------------------------------------------------------------------

  it('catches cleanup errors per-task, pushes to failures, does not re-throw', async () => {
    const tasks = [
      createMockTask('task-ok'),
      createMockTask('task-throws'),
      createMockTask('task-ok-2'),
    ];
    taskRepo = createMockTaskRepo(tasks);
    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      attachments: attachmentRepo,
      swimlanes: { list: vi.fn(() => []), getById: vi.fn() },
      actions: { getTransitionsFor: vi.fn(() => []) },
    });

    // task-throws: cleanupTaskResources throws
    mockCleanupTaskResources.mockImplementation(
      async (_ctx: unknown, task: { id: string }) => {
        if (task.id === 'task-throws') throw new Error('PTY hang on cleanup');
      },
    );
    mockExistsSync.mockReturnValue(false);

    const result = await callBulkDeleteHandler(context, ['task-ok', 'task-throws', 'task-ok-2']);

    // Handler must not throw (verified implicitly - if it threw the test would fail)
    expect(result.failures).toHaveLength(1);
    expect(result.failures[0].id).toBe('task-throws');
    expect(result.failures[0].error).toBe('PTY hang on cleanup');

    // The two successful tasks still deleted
    expect(result.deleted).toBe(2);

    // completed counter reached 3 even though one failed (finally block increments)
    const progressCalls = context.mainWindow.webContents.send.mock.calls.filter(
      (call) => call[0] === IPC.TASK_BULK_DELETE_PROGRESS,
    );
    const lastPayload = progressCalls[progressCalls.length - 1][1] as {
      completed: number;
      total: number;
      failures: Array<{ id: string; error: string }>;
    };
    expect(lastPayload.completed).toBe(3);
    expect(lastPayload.total).toBe(3);
    expect(lastPayload.failures).toHaveLength(1);
  });

  // -------------------------------------------------------------------------
  // Error message coercion: non-Error throws are stringified
  // -------------------------------------------------------------------------

  it('coerces non-Error throw to string in failure message', async () => {
    const task = createMockTask('task-string-throw');
    taskRepo = createMockTaskRepo([task]);
    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      attachments: attachmentRepo,
      swimlanes: { list: vi.fn(() => []), getById: vi.fn() },
      actions: { getTransitionsFor: vi.fn(() => []) },
    });

    mockCleanupTaskResources.mockRejectedValue('something went wrong');
    mockExistsSync.mockReturnValue(false);

    const result = await callBulkDeleteHandler(context, ['task-string-throw']);

    expect(result.failures[0].error).toBe('something went wrong');
  });

  // -------------------------------------------------------------------------
  // Mixed scenario: orphan + throw + clean
  // -------------------------------------------------------------------------

  it('handles a mix of orphan, throw, and clean deletions correctly', async () => {
    const orphanPath = '/mock/project/.kangentic/worktrees/task-orphan2-abcd';
    const tasks = [
      createMockTask('task-orphan2', { worktree_path: orphanPath }),
      createMockTask('task-throws2'),
      createMockTask('task-clean2'),
    ];
    taskRepo = createMockTaskRepo(tasks);
    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      attachments: attachmentRepo,
      swimlanes: { list: vi.fn(() => []), getById: vi.fn() },
      actions: { getTransitionsFor: vi.fn(() => []) },
    });

    mockCleanupTaskResources.mockImplementation(
      async (_ctx: unknown, task: { id: string }) => {
        if (task.id === 'task-throws2') throw new Error('locked');
      },
    );
    mockExistsSync.mockImplementation((p: string) => p === orphanPath);

    const result = await callBulkDeleteHandler(context, ['task-orphan2', 'task-throws2', 'task-clean2']);

    expect(result.failures).toHaveLength(2);
    const failureIds = result.failures.map((failure) => failure.id);
    expect(failureIds).toContain('task-orphan2');
    expect(failureIds).toContain('task-throws2');
    expect(result.deleted).toBe(1);
  });

  // -------------------------------------------------------------------------
  // mainWindow.isDestroyed() guard: no send when window is destroyed
  // -------------------------------------------------------------------------

  it('skips IPC send when mainWindow is destroyed', async () => {
    context.mainWindow.isDestroyed.mockReturnValue(true);
    const task = createMockTask('task-destroyed');
    taskRepo = createMockTaskRepo([task]);
    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      attachments: attachmentRepo,
      swimlanes: { list: vi.fn(() => []), getById: vi.fn() },
      actions: { getTransitionsFor: vi.fn(() => []) },
    });
    mockCleanupTaskResources.mockResolvedValue(undefined);
    mockExistsSync.mockReturnValue(false);

    const result = await callBulkDeleteHandler(context, ['task-destroyed']);

    expect(result.deleted).toBe(1);
    expect(context.mainWindow.webContents.send).not.toHaveBeenCalled();
  });
});
