/**
 * `notifyBranchCheckoutBlocked` sends `task:spawnBlocked` only for a
 * `BranchCheckoutBlockedError`, and stamps it with an EXPLICIT `projectId`
 * whenever the caller supplies one - never falling back to the ambient
 * `context.currentProjectId` in that case. The MCP auto-spawn path
 * (`agent-spawn.ts`) depends on this: it targets whichever project the tool
 * named, which is often not the focused project, so `projectId ??
 * context.currentProjectId` must resolve to the EXPLICIT id when both are
 * present. Every other call site stubs this function as a bare `vi.fn()` and
 * never inspects its arguments, so this file is the only place the `??`
 * order (and the two early-return guards) is pinned.
 */

import { describe, it, expect, vi } from 'vitest';

vi.mock('../../src/main/git/worktree-manager', () => ({
  WorktreeManager: class {},
}));

vi.mock('../../src/main/git/git-checks', () => ({
  isGitRepo: vi.fn(() => true),
  hasCommits: vi.fn(async () => true),
  isAutoGeneratedBranch: vi.fn(() => false),
}));

vi.mock('../../src/main/git/fetch-throttle', () => ({ fetchIfStale: vi.fn(async () => 'main') }));

vi.mock('simple-git', () => ({
  default: () => ({ raw: vi.fn(async () => '') }),
}));

import { notifyBranchCheckoutBlocked, BranchCheckoutBlockedError } from '../../src/main/ipc/helpers/task-git';
import { IPC } from '../../src/shared/ipc-channels';
import type { IpcContext } from '../../src/main/ipc/ipc-context';
import type { Task } from '../../src/shared/types';

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: 'aaaa1111-0000-0000-0000-000000000000',
    display_id: 1,
    title: 'A task',
    ...overrides,
  } as Task;
}

function makeBlockedError(): BranchCheckoutBlockedError {
  return new BranchCheckoutBlockedError('/mock/project', 'blocking-task-id', 'Blocking task');
}

describe('notifyBranchCheckoutBlocked', () => {
  it('sends with the EXPLICIT projectId when it differs from context.currentProjectId', () => {
    const send = vi.fn();
    const context = {
      mainWindow: { isDestroyed: () => false, webContents: { send } },
      currentProjectId: 'ambient-project',
    } as unknown as IpcContext;
    const task = makeTask();
    const error = makeBlockedError();

    notifyBranchCheckoutBlocked(context, task, error, 'explicit-project');

    expect(send).toHaveBeenCalledWith(
      IPC.TASK_SPAWN_BLOCKED,
      task.id,
      task.title,
      error.message,
      'explicit-project',
    );
  });

  it('falls back to context.currentProjectId when no explicit projectId is passed', () => {
    const send = vi.fn();
    const context = {
      mainWindow: { isDestroyed: () => false, webContents: { send } },
      currentProjectId: 'ambient-project',
    } as unknown as IpcContext;
    const task = makeTask();
    const error = makeBlockedError();

    notifyBranchCheckoutBlocked(context, task, error);

    expect(send).toHaveBeenCalledWith(
      IPC.TASK_SPAWN_BLOCKED,
      task.id,
      task.title,
      error.message,
      'ambient-project',
    );
  });

  it('sends nothing for an error that is not a BranchCheckoutBlockedError', () => {
    const send = vi.fn();
    const context = {
      mainWindow: { isDestroyed: () => false, webContents: { send } },
      currentProjectId: 'ambient-project',
    } as unknown as IpcContext;
    const task = makeTask();

    notifyBranchCheckoutBlocked(context, task, new Error('some other git failure'), 'explicit-project');

    expect(send).not.toHaveBeenCalled();
  });

  it('sends nothing when context.mainWindow is null', () => {
    const context = {
      mainWindow: null,
      currentProjectId: 'ambient-project',
    } as unknown as IpcContext;
    const task = makeTask();
    const error = makeBlockedError();

    // Must not throw either: a removed null-guard would dereference
    // `context.mainWindow.isDestroyed()` on a null mainWindow.
    expect(() => notifyBranchCheckoutBlocked(context, task, error, 'explicit-project')).not.toThrow();
  });

  it('sends nothing when context.mainWindow.isDestroyed() returns true', () => {
    const send = vi.fn();
    const context = {
      mainWindow: { isDestroyed: () => true, webContents: { send } },
      currentProjectId: 'ambient-project',
    } as unknown as IpcContext;
    const task = makeTask();
    const error = makeBlockedError();

    notifyBranchCheckoutBlocked(context, task, error, 'explicit-project');

    expect(send).not.toHaveBeenCalled();
  });
});
