/**
 * Unit tests for the link-time PR resolve on the TASK_UPDATE IPC handler.
 *
 * TASK_UPDATE is the main-process sink for the task-detail edit form: its
 * `buildPrFields` writes pr_url + pr_number with pr_state deliberately null, so
 * a stale terminal state cannot freeze a re-pointed link. Nothing then refilled
 * that state promptly, which left the board card showing a bare PR pill with no
 * state chip until the background sweep ran. The handler now fires a forced
 * resolve right after the write.
 *
 * Pattern mirrors task-create-handler.test.ts: capture the function registered
 * with ipcMain.handle and invoke it directly, with every dependency mocked so
 * no Electron binary or real filesystem is needed.
 *
 * Covers:
 *   - a write that SETS a link resolves, forced and preserving the link
 *   - a write that CLEARS a link does not resolve (the ladder's branch/commit
 *     tiers would re-link the task and bounce the clear straight back)
 *   - an edit that does not touch the PR fields does not resolve
 *   - the renderer's explicit projectId is what the resolve is routed by
 *   - a failing resolve never fails the update
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ---------------------------------------------------------------------------
// Hoisted mocks
// ---------------------------------------------------------------------------

vi.mock('electron', () => ({
  ipcMain: {
    handle: vi.fn((channel: string, handler: (...args: unknown[]) => unknown) => {
      capturedHandlers.set(channel, handler);
    }),
  },
}));

vi.mock('node:fs', () => ({
  default: {
    existsSync: vi.fn(() => false),
  },
}));

vi.mock('simple-git', () => ({
  simpleGit: vi.fn(() => ({})),
  default: vi.fn(() => ({})),
}));

vi.mock('../../src/main/db/database', () => ({ getProjectDb: vi.fn(() => ({})) }));
vi.mock('../../src/main/db/repositories/task-repository', () => ({
  TaskRepository: class {},
}));
vi.mock('../../src/main/db/repositories/session-repository', () => ({
  SessionRepository: class {},
}));
vi.mock('../../src/main/db/repositories/swimlane-repository', () => ({
  SwimlaneRepository: class {},
}));
vi.mock('../../src/main/db/repositories/action-repository', () => ({
  ActionRepository: class {},
}));
vi.mock('../../src/main/db/repositories/attachment-repository', () => ({
  AttachmentRepository: class {},
}));

vi.mock('../../src/main/git/worktree-manager', () => ({
  WorktreeManager: class {
    withLock = vi.fn(async (fn: () => Promise<unknown>) => fn());
    renameBranch = vi.fn(async () => null);
  },
}));

vi.mock('../../src/main/git/git-checks', () => ({
  isAutoGeneratedBranch: vi.fn(() => false),
}));

vi.mock('../../src/main/git/fetch-throttle', () => ({
  fetchIfStale: vi.fn(async () => 'main'),
}));

vi.mock('../../src/main/git/node-modules-link', () => ({
  linkNodeModules: vi.fn(),
  removeNodeModulesPath: vi.fn(),
}));

vi.mock('../../src/main/config/config-manager', () => ({
  ConfigManager: class {
    getEffectiveConfig = vi.fn(() => ({ git: { defaultBaseBranch: 'main' } }));
  },
}));

const mockGetProjectRepos = vi.fn();

vi.mock('../../src/main/ipc/helpers', () => ({
  getProjectRepos: (...args: unknown[]) => mockGetProjectRepos(...args),
  ensureTaskWorktree: vi.fn(async () => null),
  ensureTaskBranchCheckout: vi.fn(async () => {}),
  notifyBranchCheckoutBlocked: () => {},
  createTransitionEngine: vi.fn(),
  cleanupTaskResources: vi.fn(async () => {}),
  spawnAgent: vi.fn(async () => {}),
}));

vi.mock('../../src/main/agent/shared', () => ({
  interpolateTemplate: vi.fn((template: string) => template),
  resolveBridgeScript: vi.fn(() => '/mock/bridge.js'),
  execVersion: vi.fn(async () => '1.0.0'),
}));

vi.mock('../../src/main/ipc/handlers/task-move', () => ({
  handleTaskMove: vi.fn(async () => {}),
}));

// The factory replaces the whole module, which is why the "did this write set a
// link?" gate lives inline in the handler rather than being exported from here.
const mockLinkPR = vi.fn(async () => ({ status: 'unchanged', task: null }));

vi.mock('../../src/main/pr/pr-linking', () => ({
  linkPR: (...args: unknown[]) => mockLinkPR(...(args as [])),
  autoLinkPRForTask: vi.fn(),
}));

// ---------------------------------------------------------------------------
// Capture handlers registered by ipcMain.handle
// ---------------------------------------------------------------------------

const capturedHandlers = new Map<string, (...args: unknown[]) => unknown>();

// ---------------------------------------------------------------------------
// Import under test (after all mocks are registered)
// ---------------------------------------------------------------------------

import { registerTaskCrudHandlers } from '../../src/main/ipc/handlers/task-crud';
import { IPC } from '../../src/shared/ipc-channels';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const LINKED_PR_URL = 'https://github.com/owner/repo/pull/240';

/** The row as it stands before the update - already linked, so a clear is testable. */
function createExistingTask(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    id: 'task-1',
    title: 'Fix the badge',
    branch_name: null,
    worktree_path: null,
    base_branch: null,
    pr_url: LINKED_PR_URL,
    pr_number: 240,
    pr_state: null,
    ...overrides,
  };
}

function createMockContext(): Record<string, unknown> {
  return {
    currentProjectId: 'proj-123',
    currentProjectPath: '/mock/project',
    mainWindow: {
      isDestroyed: vi.fn(() => false),
      webContents: { send: vi.fn() },
    },
    sessionManager: {
      listSessions: vi.fn(() => []),
      getActivityCache: vi.fn(() => ({})),
    },
    configManager: {
      getEffectiveConfig: vi.fn(() => ({ git: { defaultBaseBranch: 'main' } })),
    },
    boardConfigManager: {
      getDefaultBaseBranch: vi.fn(() => null),
      getBoardProfiles: vi.fn(() => []),
    },
    terminalSubmitScheduler: { scheduleKeystrokes: vi.fn() },
    projectRepo: { getById: vi.fn(() => ({ id: 'proj-123', path: '/mock/project' })) },
  };
}

async function callUpdateHandler(
  input: Record<string, unknown>,
  projectId: string | null = 'proj-123',
): Promise<Record<string, unknown>> {
  const handler = capturedHandlers.get(IPC.TASK_UPDATE);
  if (!handler) throw new Error(`Handler for ${IPC.TASK_UPDATE} was not registered`);
  return await (handler(null, input, projectId) as Promise<Record<string, unknown>>);
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe('TASK_UPDATE link-time PR resolve', () => {
  let mockTaskUpdate: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    vi.clearAllMocks();
    capturedHandlers.clear();

    mockLinkPR.mockResolvedValue({ status: 'unchanged', task: null });
    const existing = createExistingTask();
    mockTaskUpdate = vi.fn((patch: Record<string, unknown>) => ({ ...existing, ...patch }));
    mockGetProjectRepos.mockReturnValue({
      tasks: { getById: vi.fn(() => existing), update: mockTaskUpdate },
      swimlanes: { getById: vi.fn(() => null) },
      actions: { getTransitionsFor: vi.fn(() => []) },
      attachments: { add: vi.fn() },
    });

    registerTaskCrudHandlers(createMockContext() as never);
  });

  it('resolves after a write that sets a PR link, forced and preserving the link', async () => {
    // Forced because a non-force resolve inside the 60s per-task throttle is
    // coalesced away, which is exactly the window a PR-creating flow lands in.
    // preserveLinkOnNotFound so the resolve cannot undo the write that fired it.
    await callUpdateHandler({ id: 'task-1', pr_url: LINKED_PR_URL, pr_number: 240, pr_state: null });

    expect(mockLinkPR).toHaveBeenCalledWith(
      expect.anything(),
      expect.objectContaining({
        projectId: 'proj-123',
        taskId: 'task-1',
        force: true,
        preserveLinkOnNotFound: true,
      }),
    );
  });

  it('resolves when only a PR number is written', async () => {
    await callUpdateHandler({ id: 'task-1', pr_number: 240, pr_state: null });

    expect(mockLinkPR).toHaveBeenCalledTimes(1);
  });

  it('resolves when only a PR URL is written, with no number for the URL to name', async () => {
    // The URL clause is the first half of an OR: every other test in this file
    // that reaches the gate also sets pr_number, so nothing here isolates it. A
    // URL that names no PR number (z.string().url() admits any URL, not just a
    // /pull/<n> one) is the realistic shape this clause exists for, and it is
    // the ONLY clause that can fire the resolve in that case.
    await callUpdateHandler({ id: 'task-1', pr_url: 'https://example.com/not-a-pr', pr_number: null, pr_state: null });

    expect(mockLinkPR).toHaveBeenCalledTimes(1);
  });

  it('does not resolve when the link is cleared', async () => {
    // The gate is on SETTING a link. A resolve here would fall through to the
    // ladder's branch and commit tiers, re-link the task, and bounce the user's
    // clear straight back on the next repaint.
    await callUpdateHandler({ id: 'task-1', pr_url: null, pr_number: null, pr_state: null });

    expect(mockLinkPR).not.toHaveBeenCalled();
  });

  it('does not resolve when the PR URL is written empty', async () => {
    await callUpdateHandler({ id: 'task-1', pr_url: '', pr_number: null, pr_state: null });

    expect(mockLinkPR).not.toHaveBeenCalled();
  });

  it('does not resolve on an edit that leaves the PR fields alone', async () => {
    // The task is already linked, so a gate that read the post-write row instead
    // of this call's patch would fire a `gh` round-trip on every title edit.
    await callUpdateHandler({ id: 'task-1', title: 'Renamed' });

    expect(mockLinkPR).not.toHaveBeenCalled();
  });

  it('routes the resolve by the projectId the renderer stamped, not the ambient one', async () => {
    await callUpdateHandler({ id: 'task-1', pr_url: LINKED_PR_URL, pr_number: 240 }, 'proj-other');

    expect(mockLinkPR).toHaveBeenCalledWith(
      expect.anything(),
      expect.objectContaining({ projectId: 'proj-other' }),
    );
  });

  it('returns the updated task and never fails the write when the resolve throws', async () => {
    // gh missing / unauthenticated / offline must leave the link written with a
    // null state and the save succeeding, exactly as before link-time resolving.
    mockLinkPR.mockRejectedValue(new Error('gh not found'));
    const consoleError = vi.spyOn(console, 'error').mockImplementation(() => {});

    const result = await callUpdateHandler({ id: 'task-1', pr_url: LINKED_PR_URL, pr_number: 240, pr_state: null });
    await Promise.resolve();
    await Promise.resolve();

    expect(result).toMatchObject({ pr_url: LINKED_PR_URL, pr_number: 240, pr_state: null });
    expect(mockTaskUpdate).toHaveBeenCalledTimes(1);
    consoleError.mockRestore();
  });
});
