/**
 * Unit tests for the TASK_CREATE IPC handler in task-crud.ts.
 *
 * Pattern mirrors bulk-delete-handler.test.ts: capture the function registered
 * with ipcMain.handle and invoke it directly. All dependencies are mocked so
 * no Electron binary or real filesystem is needed.
 *
 * task-lifecycle-lock is the REAL implementation so the withTaskLock wrap
 * added around TASK_CREATE's auto-spawn flow is observable.
 *
 * Covers:
 *   - auto_spawn=false on target lane: no ensureTaskWorktree, no spawnAgent;
 *     returns the created task
 *   - worktree error branch: ensureTaskWorktree throws, returns task with no
 *     spawn (lock is still acquired and released cleanly)
 *   - checkout error branch: ensureTaskBranchCheckout throws, returns task
 *     with no spawn
 *   - create-into-spawn-column routes through the shared spawnAgent
 *     chokepoint: '*' wildcard fromSwimlaneId, the creation column as toLane,
 *     projectId/projectPath threaded, and settingsSourceLane OMITTED so
 *     spawnAgent's preamble locks against the creation column itself.
 *     Engine-level behavior (transition, fallback resume, auto-command
 *     delivery, the first-spawn override lock) is spawnAgent's responsibility,
 *     covered by the spawn-agent-*.test.ts harness suites.
 *   - withTaskLock engagement: concurrent TASK_CREATE for the same task id
 *     serializes (second call waits for first)
 *   - no-project path: auto_spawn branch requires currentProjectId and
 *     currentProjectPath; null currentProjectPath short-circuits the block
 *   - pending attachments saved when provided
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

const {
  mockAgentRegistryGet,
  mockDirectGetProjectRepos,
  mockDirectEnsureTaskWorktree,
  mockDirectResumeSuspendedSession,
  mockDirectRunSpawnPreamble,
  mockGetProjectDb,
  mockSessionRepoGetLatestForTask,
  mockSessionRepoGetLatestForTaskByTypeAndIsolation,
  mockSwimlaneRepoGetById,
} = vi.hoisted(() => ({
  mockAgentRegistryGet: vi.fn(),
  mockDirectGetProjectRepos: vi.fn(),
  mockDirectEnsureTaskWorktree: vi.fn(async () => undefined),
  mockDirectResumeSuspendedSession: vi.fn(async () => undefined),
  mockDirectRunSpawnPreamble: vi.fn(() => ({ agent: 'mock-agent', isHandoff: false })),
  mockGetProjectDb: vi.fn(() => ({})),
  mockSessionRepoGetLatestForTask: vi.fn(() => undefined),
  mockSessionRepoGetLatestForTaskByTypeAndIsolation: vi.fn(() => undefined),
  mockSwimlaneRepoGetById: vi.fn(),
}));

// ---------------------------------------------------------------------------
// Hoisted mocks
// ---------------------------------------------------------------------------

vi.mock('electron', () => ({
  ipcMain: {
    handle: vi.fn((channel: string, handler: (...args: unknown[]) => unknown) => {
      capturedHandlers.set(channel, handler);
    }),
  },
}));

vi.mock('node:fs', () => ({
  default: {
    existsSync: vi.fn(() => false),
  },
}));

// p-queue is NOT mocked here. task-lifecycle-lock uses the real p-queue
// (concurrency:1) to provide actual serialization. Stubbing p-queue would
// cause withTaskLock to run all tasks inline (no queuing), which would make
// the lock-serialization assertion at the bottom of this file vacuously true.
// TASK_CREATE does not use PQueue directly (only TASK_BULK_DELETE does), so
// leaving p-queue real has no side effects here.

vi.mock('simple-git', () => ({
  simpleGit: vi.fn(() => ({})),
  default: vi.fn(() => ({})),
}));

vi.mock('../../src/main/db/database', () => ({ getProjectDb: mockGetProjectDb }));
vi.mock('../../src/main/db/repositories/task-repository', () => ({
  TaskRepository: class {},
}));
vi.mock('../../src/main/db/repositories/session-repository', () => ({
  SessionRepository: class {
    getLatestForTask = mockSessionRepoGetLatestForTask;
    getLatestForTaskByTypeAndIsolation = mockSessionRepoGetLatestForTaskByTypeAndIsolation;
  },
}));
vi.mock('../../src/main/db/repositories/swimlane-repository', () => ({
  SwimlaneRepository: class {
    getById = mockSwimlaneRepoGetById;
  },
}));
vi.mock('../../src/main/db/repositories/action-repository', () => ({
  ActionRepository: class {},
}));
vi.mock('../../src/main/db/repositories/attachment-repository', () => ({
  AttachmentRepository: class {},
}));

vi.mock('../../src/main/git/worktree-manager', () => ({
  WorktreeManager: class {
    withLock = vi.fn(async (fn: () => Promise<unknown>) => fn());
    renameBranch = vi.fn(async () => null);
  },
}));

vi.mock('../../src/main/git/git-checks', () => ({
  isAutoGeneratedBranch: vi.fn(() => false),
}));

vi.mock('../../src/main/git/fetch-throttle', () => ({
  fetchIfStale: vi.fn(async () => 'main'),
}));

vi.mock('../../src/main/git/node-modules-link', () => ({
  linkNodeModules: vi.fn(),
  removeNodeModulesPath: vi.fn(),
}));

vi.mock('../../src/main/config/config-manager', () => ({
  ConfigManager: class {
    getEffectiveConfig = vi.fn(() => ({ git: { defaultBaseBranch: 'main' } }));
  },
}));

// task-lifecycle-lock: use the REAL implementation so lock semantics are preserved.
// TASK_CREATE wraps its auto-spawn flow in withTaskLock.

// Mocked helpers - configured per test
const mockGetProjectRepos = vi.fn();
const mockEnsureTaskWorktree = vi.fn(async () => null);
const mockEnsureTaskBranchCheckout = vi.fn(async () => {});
const mockCreateTransitionEngine = vi.fn();
const mockCleanupTaskResources = vi.fn(async () => {});
const mockSpawnAgent = vi.fn(async () => {});

vi.mock('../../src/main/ipc/helpers', () => ({
  getProjectRepos: (...args: unknown[]) => mockGetProjectRepos(...args),
  ensureTaskWorktree: (...args: unknown[]) => mockEnsureTaskWorktree(...args),
  ensureTaskBranchCheckout: (...args: unknown[]) => mockEnsureTaskBranchCheckout(...args),
  createTransitionEngine: (...args: unknown[]) => mockCreateTransitionEngine(...args),
  cleanupTaskResources: (...args: unknown[]) => mockCleanupTaskResources(...args),
  spawnAgent: (...args: unknown[]) => mockSpawnAgent(...args),
}));

vi.mock('../../src/main/agent/shared', async () => {
  const { interpolateTaskTemplate } = await import('../../src/main/agent/shared/template-utils');

  return {
    interpolateTemplate: vi.fn((template: string) => template),
    interpolateTaskTemplate,
    resolveTaskTemplateVars: vi.fn(() => ({})),
    resolveBridgeScript: vi.fn(() => '/mock/bridge.js'),
    execVersion: vi.fn(async () => '1.0.0'),
  };
});

vi.mock('../../src/main/ipc/handlers/task-move', () => ({
  guardActiveNonWorktreeSessions: vi.fn(),
  handleTaskMove: vi.fn(async () => {}),
}));

vi.mock('../../src/main/agent/agent-registry', () => ({
  agentRegistry: { get: mockAgentRegistryGet },
}));

vi.mock('../../src/main/ipc/helpers/project-repos', () => ({
  getProjectRepos: mockDirectGetProjectRepos,
  resolveProjectContext: (context: { currentProjectId: string | null; currentProjectPath: string | null }, projectId?: string | null) => ({
    projectId: projectId ?? context.currentProjectId,
    projectPath: context.currentProjectPath,
  }),
}));

vi.mock('../../src/main/ipc/helpers/task-git', () => ({
  ensureTaskWorktree: mockDirectEnsureTaskWorktree,
  ensureTaskBranchCheckout: vi.fn(async () => undefined),
}));

vi.mock('../../src/main/transition-engine/spawn-preamble', () => ({
  runSpawnPreamble: mockDirectRunSpawnPreamble,
}));

vi.mock('../../src/main/transition-engine/transition-engine', () => ({
  TransitionEngine: class {
    executeTransition = vi.fn(async () => undefined);
    resumeSuspendedSession = mockDirectResumeSuspendedSession;
  },
}));

vi.mock('../../src/main/diagnostics/project-log-context', () => ({
  runWithProjectLogContext: <T>(_projectName: string, run: () => Promise<T>): Promise<T> => run(),
}));

// ---------------------------------------------------------------------------
// Capture handlers registered by ipcMain.handle
// ---------------------------------------------------------------------------

const capturedHandlers = new Map<string, (...args: unknown[]) => unknown>();

// ---------------------------------------------------------------------------
// Import under test (after all mocks are registered)
// ---------------------------------------------------------------------------

import { registerTaskCrudHandlers } from '../../src/main/ipc/handlers/task-crud';
import { autoSpawnForTask } from '../../src/main/ipc/helpers/agent-spawn';
import { _taskLockCountForTesting } from '../../src/main/ipc/task-lifecycle-lock';
import { IPC } from '../../src/shared/ipc-channels';

// ---------------------------------------------------------------------------
// Helper types
// ---------------------------------------------------------------------------

interface MockTask {
  id: string;
  title: string;
  swimlane_id: string;
  worktree_path: string | null;
  session_id: string | null;
  branch_name: string | null;
  base_branch: string | null;
  /** Per-task auto_command (MCP-only, kangentic_create_task's autoCommand param).
   *  Wins over the destination swimlane's auto_command for this task only. */
  auto_command: string | null;
}

interface MockSwimlane {
  id: string;
  role: string | null;
  auto_spawn: boolean;
  auto_command: string | null;
  permission_mode: string | null;
}

interface MockTaskRepo {
  clearAutoCommand: ReturnType<typeof vi.fn>;
  create: ReturnType<typeof vi.fn>;
  getById: ReturnType<typeof vi.fn>;
  list: ReturnType<typeof vi.fn>;
  delete: ReturnType<typeof vi.fn>;
}

interface MockAttachmentRepo {
  add: ReturnType<typeof vi.fn>;
  deleteByTaskId: ReturnType<typeof vi.fn>;
}

interface MockSwimlaneRepo {
  list: ReturnType<typeof vi.fn>;
  getById: ReturnType<typeof vi.fn>;
}

interface MockEngine {
  executeTransition: ReturnType<typeof vi.fn>;
  resumeSuspendedSession: ReturnType<typeof vi.fn>;
}

interface MockContext {
  currentProjectId: string | null;
  currentProjectPath: string | null;
  mainWindow: {
    isDestroyed: ReturnType<typeof vi.fn>;
    webContents: { send: ReturnType<typeof vi.fn> };
  };
  sessionManager: {
    listSessions: ReturnType<typeof vi.fn>;
    getActivityCache: ReturnType<typeof vi.fn>;
  };
  configManager: {
    getEffectiveConfig: ReturnType<typeof vi.fn>;
  };
  boardConfigManager: {
    getDefaultBaseBranch: ReturnType<typeof vi.fn>;
    getBoardProfiles: ReturnType<typeof vi.fn>;
  };
  terminalSubmitScheduler: {
    scheduleKeystrokes: ReturnType<typeof vi.fn>;
  };
  projectRepo: {
    getById: ReturnType<typeof vi.fn>;
  };
}

function createMockTask(id: string, overrides: Partial<MockTask> = {}): MockTask {
  return {
    id,
    title: `Task ${id}`,
    swimlane_id: 'lane-doing',
    worktree_path: null,
    session_id: null,
    branch_name: null,
    base_branch: null,
    auto_command: null,
    ...overrides,
  };
}

function createMockSwimlane(id: string, overrides: Partial<MockSwimlane> = {}): MockSwimlane {
  return {
    id,
    role: null,
    auto_spawn: true,
    auto_command: null,
    permission_mode: null,
    ...overrides,
  };
}

function createMockTaskRepo(task: MockTask): MockTaskRepo {
  // Stored task reflects updates (e.g. session_id set by the engine)
  let storedTask = { ...task };
  return {
    clearAutoCommand: vi.fn((taskId: string) => {
      if (taskId === storedTask.id) {
        storedTask = { ...storedTask, auto_command: null };
      }
    }),
    create: vi.fn((_input: unknown) => storedTask),
    getById: vi.fn((_id: string) => storedTask),
    list: vi.fn(() => [storedTask]),
    delete: vi.fn(),
    // Test helper: allow tests to update the stored task between calls
    _setStoredTask: (updated: MockTask) => { storedTask = updated; },
  } as unknown as MockTaskRepo;
}

function createMockAttachmentRepo(): MockAttachmentRepo {
  return {
    add: vi.fn(),
    deleteByTaskId: vi.fn(),
  };
}

function createMockSwimlaneRepo(swimlanes: MockSwimlane[]): MockSwimlaneRepo {
  const laneMap = new Map(swimlanes.map((lane) => [lane.id, lane]));
  return {
    list: vi.fn(() => Array.from(laneMap.values())),
    getById: vi.fn((id: string) => laneMap.get(id) ?? null),
  };
}

function createMockEngine(): MockEngine {
  return {
    executeTransition: vi.fn(async () => {}),
    resumeSuspendedSession: vi.fn(async () => {}),
  };
}

function createMockContext(overrides: Partial<MockContext> = {}): MockContext {
  return {
    currentProjectId: 'proj-123',
    currentProjectPath: '/mock/project',
    mainWindow: {
      isDestroyed: vi.fn(() => false),
      webContents: { send: vi.fn() },
    },
    sessionManager: {
      listSessions: vi.fn(() => []),
      getActivityCache: vi.fn(() => ({})),
    },
    configManager: {
      getEffectiveConfig: vi.fn(() => ({ git: { defaultBaseBranch: 'main' }, agent: { permissionMode: 'acceptEdits' } })),
    },
    boardConfigManager: {
      getDefaultBaseBranch: vi.fn(() => null),
      getBoardProfiles: vi.fn(() => []),
    },
    terminalSubmitScheduler: {
      scheduleKeystrokes: vi.fn(),
    },
    projectRepo: {
      getById: vi.fn(() => ({ id: 'proj-123', default_agent: 'claude', default_model: null, default_effort: null })),
    },
    ...overrides,
  };
}

async function callCreateHandler<T = unknown>(context: MockContext, input: Record<string, unknown>): Promise<T> {
  const handler = capturedHandlers.get(IPC.TASK_CREATE);
  if (!handler) throw new Error(`Handler for ${IPC.TASK_CREATE} was not registered`);
  return handler(null, input) as Promise<T>;
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe('TASK_CREATE handler', () => {
  let context: MockContext;
  let task: MockTask;
  let taskRepo: MockTaskRepo;
  let attachmentRepo: MockAttachmentRepo;
  let swimlaneRepo: MockSwimlaneRepo;
  let targetLane: MockSwimlane;

  beforeEach(() => {
    vi.clearAllMocks();
    capturedHandlers.clear();

    targetLane = createMockSwimlane('lane-doing', { auto_spawn: true });
    task = createMockTask('task-new', { swimlane_id: 'lane-doing' });
    taskRepo = createMockTaskRepo(task);
    attachmentRepo = createMockAttachmentRepo();
    swimlaneRepo = createMockSwimlaneRepo([targetLane]);
    context = createMockContext();

    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      swimlanes: swimlaneRepo,
      actions: { getTransitionsFor: vi.fn(() => []) },
      attachments: attachmentRepo,
    });

    mockEnsureTaskWorktree.mockResolvedValue(null);
    mockEnsureTaskBranchCheckout.mockResolvedValue(undefined);

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    registerTaskCrudHandlers(context as never);
  });

  // =========================================================================
  // auto_spawn=false: skips entire lock block
  // =========================================================================

  it('skips worktree, transition, and auto-command when target lane has auto_spawn=false', async () => {
    const noSpawnLane = createMockSwimlane('lane-backlog', { auto_spawn: false });
    swimlaneRepo = createMockSwimlaneRepo([noSpawnLane]);
    const noSpawnTask = createMockTask('task-no-spawn', { swimlane_id: 'lane-backlog' });
    taskRepo = createMockTaskRepo(noSpawnTask);

    mockGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      swimlanes: swimlaneRepo,
      actions: { getTransitionsFor: vi.fn(() => []) },
      attachments: attachmentRepo,
    });

    const result = await callCreateHandler(context, {
      swimlane_id: 'lane-backlog',
      title: 'No spawn task',
    });

    expect(result).toMatchObject({ id: 'task-no-spawn' });
    expect(mockEnsureTaskWorktree).not.toHaveBeenCalled();
    expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
    expect(mockSpawnAgent).not.toHaveBeenCalled();
  });

  it('skips lock block when currentProjectPath is null', async () => {
    context.currentProjectPath = null;
    capturedHandlers.clear();
    registerTaskCrudHandlers(context as never);

    const result = await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'No path task',
    });

    expect(result).toMatchObject({ id: 'task-new' });
    expect(mockEnsureTaskWorktree).not.toHaveBeenCalled();
    expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
  });

  it('skips lock block when currentProjectId is null', async () => {
    context.currentProjectId = null;
    capturedHandlers.clear();
    registerTaskCrudHandlers(context as never);

    const result = await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'No project task',
    });

    expect(result).toMatchObject({ id: 'task-new' });
    expect(mockEnsureTaskWorktree).not.toHaveBeenCalled();
  });

  // =========================================================================
  // Worktree error branch
  // =========================================================================

  it('returns task without spawning when ensureTaskWorktree throws (lock released cleanly)', async () => {
    mockEnsureTaskWorktree.mockRejectedValue(new Error('git worktree add failed'));

    const result = await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Worktree error task',
    });

    expect(result).toMatchObject({ id: 'task-new' });
    expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
    expect(mockSpawnAgent).not.toHaveBeenCalled();
  });

  // =========================================================================
  // Checkout error branch
  // =========================================================================

  it('returns task without spawning when ensureTaskBranchCheckout throws', async () => {
    mockEnsureTaskBranchCheckout.mockRejectedValue(new Error('branch locked by active session'));

    const result = await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Checkout error task',
    });

    expect(result).toMatchObject({ id: 'task-new' });
    expect(mockCreateTransitionEngine).not.toHaveBeenCalled();
    expect(mockSpawnAgent).not.toHaveBeenCalled();
  });

  // =========================================================================
  // Create-into-spawn-column routes through the shared spawnAgent chokepoint
  //
  // A task created directly in a spawn column must take the SAME path as
  // every other spawn entry point (move, promote, MCP create, unarchive):
  // spawnAgent, whose preamble locks the Advanced overrides and resolves the
  // agent BEFORE the engine runs. Red-green: on the pre-consolidation handler
  // (its own executeTransition + lock + auto-command block), spawnAgent is
  // never called and this fails. See
  // .claude/rules/spawn-entry-point-parity.md.
  // =========================================================================

  it('routes through spawnAgent with "*" wildcard, the creation column as toLane, and NO settingsSourceLane', async () => {
    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Spawn routing task',
    });

    expect(mockSpawnAgent).toHaveBeenCalledTimes(1);
    const spawnArg = mockSpawnAgent.mock.calls[0][0] as {
      context: MockContext;
      engine: MockEngine;
      tasks: MockTaskRepo;
      task: { id: string };
      fromSwimlaneId: string;
      toLane: MockSwimlane;
      projectId: string;
      projectPath: string;
    };
    expect(spawnArg.task).toMatchObject({ id: 'task-new' });
    // No source column on creation - matches wildcard transitions.
    expect(spawnArg.fromSwimlaneId).toBe('*');
    // The creation column IS the destination (and, via spawnAgent's
    // settingsSourceLane fallback, the settings lane the lock resolves
    // against) - so settingsSourceLane must be OMITTED, not null: null would
    // mean "the settings lane no longer resolves" and skip the lane entirely.
    expect('settingsSourceLane' in spawnArg).toBe(false);
    expect(spawnArg.toLane).toBe(targetLane);
    // Project context threaded so the preamble sees project defaults.
    expect(spawnArg.projectId).toBe('proj-123');
    expect(spawnArg.projectPath).toBe('/mock/project');
    // The engine and repos the handler constructed are handed through.
    expect(spawnArg.engine).toBe(engine);
    expect(spawnArg.tasks).toBe(taskRepo);
  });

  it('consumes a skipped MCP task auto-command exactly once while the caller-held lock is active', async () => {
    task = createMockTask('task-mcp-auto-command', {
      auto_command: '/review',
      swimlane_id: 'lane-doing',
    });
    taskRepo = createMockTaskRepo(task);
    targetLane = createMockSwimlane('lane-doing', {
      auto_command: '/lane-command',
      auto_spawn: true,
    });
    context.projectRepo.getById.mockReturnValue({
      id: 'proj-123',
      name: 'Example project',
      path: '/mock/project',
      default_agent: 'mock-agent',
      default_model: null,
      default_effort: null,
    });
    mockDirectGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      actions: {},
      attachments: {
        getPathsForTask: vi.fn(() => []),
      },
    });
    mockSwimlaneRepoGetById.mockReturnValue(targetLane);
    mockAgentRegistryGet.mockReturnValue({
      sessionType: 'mock-session',
      getAutoCommandDisposition: () => ({
        kind: 'skip',
        reason: 'fresh-not-supported',
        warning: 'Fresh sessions do not support this Auto-command.',
      }),
    });
    const lockCounts: number[] = [];
    taskRepo.clearAutoCommand.mockImplementation(() => {
      lockCounts.push(_taskLockCountForTesting());
    });

    const outcome = await autoSpawnForTask(context as never, 'proj-123', task, targetLane.id);

    expect(outcome).toEqual({
      kind: 'skipped',
      reason: 'fresh-not-supported',
      warning: 'Fresh sessions do not support this Auto-command.',
    });
    expect(taskRepo.clearAutoCommand).toHaveBeenCalledOnce();
    expect(taskRepo.clearAutoCommand).toHaveBeenCalledWith(task.id);
    expect(lockCounts).toEqual([1]);
    expect(targetLane.auto_command).toBe('/lane-command');
  });

  it('propagates a fallback spawn lifecycle failure without consuming the task override', async () => {
    task = createMockTask('task-mcp-failure', {
      auto_command: '/review',
      swimlane_id: 'lane-doing',
    });
    taskRepo = createMockTaskRepo(task);
    targetLane = createMockSwimlane('lane-doing', { auto_spawn: true });
    context.projectRepo.getById.mockReturnValue({
      id: 'proj-123',
      name: 'Example project',
      path: '/mock/project',
      default_agent: 'mock-agent',
      default_model: null,
      default_effort: null,
    });
    mockDirectGetProjectRepos.mockReturnValue({
      tasks: taskRepo,
      actions: {},
      attachments: {
        getPathsForTask: vi.fn(() => []),
      },
    });
    mockSwimlaneRepoGetById.mockReturnValue(targetLane);
    mockAgentRegistryGet.mockReturnValue(undefined);
    mockDirectResumeSuspendedSession.mockRejectedValueOnce(new Error('session launch failed'));

    await expect(
      autoSpawnForTask(context as never, 'proj-123', task, targetLane.id),
    ).rejects.toThrow('session launch failed');
    expect(taskRepo.clearAutoCommand).not.toHaveBeenCalled();
  });

  it('returns the created task even when spawnAgent rejects', async () => {
    mockSpawnAgent.mockRejectedValueOnce(new Error('CLI not found'));

    const result = await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Spawn failure task',
    });

    expect(result).toMatchObject({ id: 'task-new' });
  });

  // =========================================================================
  // Pending attachments
  // =========================================================================

  it('saves pending attachments when provided', async () => {
    const pendingAttachments = [
      { filename: 'screenshot.png', data: 'base64data', media_type: 'image/png' },
    ];

    await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Task with attachment',
      pendingAttachments,
    });

    expect(attachmentRepo.add).toHaveBeenCalledWith(
      '/mock/project',
      'task-new',
      'screenshot.png',
      'base64data',
      'image/png',
    );
  });

  it('does NOT save attachments when pendingAttachments is empty', async () => {
    await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Task no attachments',
      pendingAttachments: [],
    });

    expect(attachmentRepo.add).not.toHaveBeenCalled();
  });

  it('does NOT save attachments when currentProjectPath is null', async () => {
    context.currentProjectPath = null;
    capturedHandlers.clear();
    registerTaskCrudHandlers(context as never);

    const pendingAttachments = [
      { filename: 'photo.jpg', data: 'data', media_type: 'image/jpeg' },
    ];

    await callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Task no project path',
      pendingAttachments,
    });

    expect(attachmentRepo.add).not.toHaveBeenCalled();
  });

  // =========================================================================
  // withTaskLock engagement: concurrent TASK_CREATE for the same task id
  // =========================================================================

  it('serializes concurrent withTaskLock calls for the same task id', async () => {
    // Use the hold pattern from task-lifecycle-lock.test.ts:
    // first invocation holds until released; second must wait.
    let releaseFirst!: () => void;
    const firstHold = new Promise<void>((resolve) => {
      releaseFirst = resolve;
    });
    const entryOrder: number[] = [];

    mockEnsureTaskWorktree.mockImplementation(async () => {
      entryOrder.push(entryOrder.length);
      if (entryOrder.length === 1) {
        await firstHold;
      }
    });

    // Both invocations share the same task.id returned by tasks.create.
    // That id is what withTaskLock keys on.
    taskRepo.getById.mockReturnValue({ ...task, session_id: null });

    const engine = createMockEngine();
    mockCreateTransitionEngine.mockReturnValue(engine);

    const first = callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'First concurrent task',
    });
    const second = callCreateHandler(context, {
      swimlane_id: 'lane-doing',
      title: 'Second concurrent task',
    });

    // Only the first invocation should have entered ensureTaskWorktree yet
    await Promise.resolve();
    expect(entryOrder).toHaveLength(1);

    releaseFirst();
    await Promise.all([first, second]);

    // Both entered, in submission order
    expect(entryOrder).toHaveLength(2);
    expect(entryOrder).toEqual([0, 1]);
  });
});
