/**
 * Unit test for the remote-execution worktree skip added to
 * `ensureTaskWorktree` (task-git.ts): a task whose resolved agent is set to
 * 'remote' execution for the current project must not get a local worktree
 * created - the agent runs against the configured server directory instead.
 *
 * Also covers the `hasCommits` early-return guard `ensureTaskBranchCheckout`
 * keeps for itself: a repo with an unborn HEAD (no commits) has nothing to
 * branch from, so branch checkout would fail on the ref - the guard skips
 * that work entirely rather than letting the failure propagate.
 * `ensureTaskWorktree`'s own no-commits (and base-branch-resolution) guard
 * moved into `WorktreeManager.ensureWorktree` so every caller shares it; it
 * is covered by `tests/unit/worktree-base-branch.test.ts` instead, since
 * `WorktreeManager` is mocked away entirely in this file.
 *
 * WorktreeManager and git-checks are mocked entirely so this test never
 * touches git or the filesystem; it only asserts whether `ensureWorktree()` /
 * `checkoutBranch()` were called.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { ensureTaskWorktree, ensureTaskBranchCheckout } from '../../src/main/ipc/helpers/task-git';
import type { IpcContext } from '../../src/main/ipc/ipc-context';
import type { Task, AppConfig, Project } from '../../src/shared/types';
import { DEFAULT_CONFIG } from '../../src/shared/types';

const ensureWorktreeMock = vi.fn().mockResolvedValue({ worktreePath: '/local/worktree/feature-x-abcd1234', branchName: 'feature-x' });
const checkoutBranchMock = vi.fn().mockResolvedValue(undefined);
const withLockMock = vi.fn((fn: () => unknown) => fn());

vi.mock('../../src/main/git/worktree-manager', () => ({
  WorktreeManager: vi.fn().mockImplementation(function MockWorktreeManager(this: Record<string, unknown>) {
    this.withLock = withLockMock;
    this.ensureWorktree = ensureWorktreeMock;
    this.checkoutBranch = checkoutBranchMock;
  }),
}));

// hasCommits defaults to true (a normal, already-committed repo) so the pre-existing
// remote-execution-skip tests below exercise ONLY that branch, not this guard. Each
// hasCommits-guard test overrides it explicitly.
const hasCommitsMock = vi.fn().mockResolvedValue(true);
const isGitRepoMock = vi.fn().mockReturnValue(true);
const isAutoGeneratedBranchMock = vi.fn().mockReturnValue(false);

vi.mock('../../src/main/git/git-checks', () => ({
  hasCommits: (...args: unknown[]) => hasCommitsMock(...args),
  isGitRepo: (...args: unknown[]) => isGitRepoMock(...args),
  isAutoGeneratedBranch: (...args: unknown[]) => isAutoGeneratedBranchMock(...args),
}));

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: 'task-001',
    title: 'Fix the bug',
    description: '',
    swimlane_id: 'lane-1',
    position: 0,
    worktree_path: null,
    branch_name: null,
    base_branch: null,
    use_worktree: null,
    agent: null,
    agent_override: null,
    model_override: null,
    effort_override: null,
    permission_mode: null,
    session_id: null,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
    is_ghost: false,
    is_archived: false,
    priority: 0,
    display_id: 1,
    attachment_count: 0,
    labels: null,
    ...overrides,
  } as Task;
}

function makeConfig(overrides: Partial<AppConfig['agent']> = {}): AppConfig {
  return {
    ...DEFAULT_CONFIG,
    agent: { ...DEFAULT_CONFIG.agent, ...overrides },
  };
}

function makeContext(config: AppConfig, projects: Project[] = []): IpcContext {
  return {
    currentProjectPath: null,
    configManager: {
      getEffectiveConfig: vi.fn().mockReturnValue(config),
    },
    projectRepo: {
      list: vi.fn().mockReturnValue(projects),
    },
  } as unknown as IpcContext;
}

describe('ensureTaskWorktree - remote execution skip', () => {
  beforeEach(() => {
    ensureWorktreeMock.mockClear();
    withLockMock.mockClear();
    checkoutBranchMock.mockClear();
    hasCommitsMock.mockReset().mockResolvedValue(true);
    isGitRepoMock.mockReset().mockReturnValue(true);
    isAutoGeneratedBranchMock.mockReset().mockReturnValue(false);
  });

  it('creates a worktree normally when the resolved agent has no execution entry (local)', async () => {
    const context = makeContext(makeConfig());
    const task = makeTask({ agent_override: 'opencode' });

    await ensureTaskWorktree(context, task, { update: vi.fn(), getById: vi.fn().mockReturnValue(task) } as never, '/project');

    expect(ensureWorktreeMock).toHaveBeenCalledTimes(1);
  });

  it('skips worktree creation when the task-overridden agent is remote', async () => {
    const context = makeContext(makeConfig({ execution: { opencode: { mode: 'remote', workingDirectory: '/srv/project' } } }));
    const task = makeTask({ agent_override: 'opencode' });

    await ensureTaskWorktree(context, task, { update: vi.fn(), getById: vi.fn().mockReturnValue(task) } as never, '/project');

    expect(ensureWorktreeMock).not.toHaveBeenCalled();
  });

  it('falls back to the project default agent when the task has no override', async () => {
    const context = makeContext(
      makeConfig({ execution: { opencode: { mode: 'remote', workingDirectory: '/srv/project' } } }),
      [{ path: '/project', default_agent: 'opencode' } as Project],
    );
    const task = makeTask({ agent_override: null });

    await ensureTaskWorktree(context, task, { update: vi.fn(), getById: vi.fn().mockReturnValue(task) } as never, '/project');

    expect(ensureWorktreeMock).not.toHaveBeenCalled();
  });

  it('does not skip when a DIFFERENT agent is set to remote (task uses claude, opencode is remote)', async () => {
    const context = makeContext(makeConfig({ execution: { opencode: { mode: 'remote', workingDirectory: '/srv/project' } } }));
    const task = makeTask({ agent_override: 'claude' });

    await ensureTaskWorktree(context, task, { update: vi.fn(), getById: vi.fn().mockReturnValue(task) } as never, '/project');

    expect(ensureWorktreeMock).toHaveBeenCalledTimes(1);
  });

  it('creates a worktree when the resolved agent is explicitly local', async () => {
    const context = makeContext(makeConfig({ execution: { opencode: { mode: 'local', workingDirectory: null } } }));
    const task = makeTask({ agent_override: 'opencode' });

    await ensureTaskWorktree(context, task, { update: vi.fn(), getById: vi.fn().mockReturnValue(task) } as never, '/project');

    expect(ensureWorktreeMock).toHaveBeenCalledTimes(1);
  });
});

describe('ensureTaskWorktree - ensureWorktree result passthrough', () => {
  beforeEach(() => {
    ensureWorktreeMock.mockClear();
    withLockMock.mockClear();
    checkoutBranchMock.mockClear();
    hasCommitsMock.mockReset().mockResolvedValue(true);
    isGitRepoMock.mockReset().mockReturnValue(true);
    isAutoGeneratedBranchMock.mockReset().mockReturnValue(false);
  });

  it('treats a null ensureWorktree result as a true no-op: does not update the task row or mutate the task object', async () => {
    // ensureWorktree no longer needs its own hasCommits guard -- it now
    // relies entirely on WorktreeManager.ensureWorktree returning null (the
    // no-commits / worktrees-disabled / already-has-worktree cases all
    // collapse to this same signal). ensureTaskWorktree must be a true no-op
    // when that happens: no DB write, no mutation of the caller's task object.
    ensureWorktreeMock.mockResolvedValueOnce(null);
    const context = makeContext(makeConfig());
    const task = makeTask();
    const originalTask = { ...task };
    const updateMock = vi.fn();

    await ensureTaskWorktree(
      context,
      task,
      { update: updateMock, getById: vi.fn().mockReturnValue(task) } as never,
      '/project',
    );

    expect(updateMock).not.toHaveBeenCalled();
    expect(task).toEqual(originalTask);
  });

  it('propagates an ensureWorktree rejection (no try/catch inside ensureTaskWorktree)', async () => {
    const failure = new Error("Cannot create worktree: this task's base branch 'release-2.0' does not exist");
    ensureWorktreeMock.mockRejectedValueOnce(failure);
    const context = makeContext(makeConfig());
    const task = makeTask();

    await expect(
      ensureTaskWorktree(
        context,
        task,
        { update: vi.fn(), getById: vi.fn().mockReturnValue(task) } as never,
        '/project',
      ),
    ).rejects.toThrow("Cannot create worktree: this task's base branch 'release-2.0' does not exist");
  });
});

describe('ensureTaskBranchCheckout - hasCommits guard', () => {
  beforeEach(() => {
    ensureWorktreeMock.mockClear();
    withLockMock.mockClear();
    checkoutBranchMock.mockClear();
    hasCommitsMock.mockReset().mockResolvedValue(true);
    isGitRepoMock.mockReset().mockReturnValue(true);
    isAutoGeneratedBranchMock.mockReset().mockReturnValue(false);
  });

  it('skips branch checkout entirely for a repo with no commits (unborn HEAD)', async () => {
    hasCommitsMock.mockResolvedValue(false);
    const task = makeTask({ worktree_path: null, branch_name: null, base_branch: 'main' });

    await ensureTaskBranchCheckout(task, '/project');

    expect(checkoutBranchMock).not.toHaveBeenCalled();
    expect(withLockMock).not.toHaveBeenCalled();
  });

  it('checks out the base branch once the repo has a commit (control case for the guard above)', async () => {
    // Same task/projectPath, only hasCommits differs - proves the skip above isn't
    // vacuous (e.g. via the "no base_branch" no-op further down).
    hasCommitsMock.mockResolvedValue(true);
    const task = makeTask({ worktree_path: null, branch_name: null, base_branch: 'main' });

    await ensureTaskBranchCheckout(task, '/project');

    expect(checkoutBranchMock).toHaveBeenCalledWith('main');
  });
});
